const maskPrice = 12.5;

export const archive = {
    // bloom: {
    //     type: 'Mask',
    //     color: 'Bloom',
    //     img: 'Bloom.jpg',
    //     param: 'bloom',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['orange', 'yellow'],
    // },
    // midnight: {
    //     type: 'Mask',
    //     color: 'Midnight',
    //     img: 'Midnight.jpg',
    //     param: 'midnight',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     // hot: true,
    //     tags: ['black', 'yellow', 'white'],
    // },
    // river: {
    //     type: 'Mask',
    //     color: 'River',
    //     img: 'River.jpg',
    //     param: 'river',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['green', 'brown'],
    // },
    // beach: {
    //     type: 'Mask',
    //     color: 'Beach',
    //     img: 'Beach.jpg',
    //     param: 'beach',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: true,
    //     tags: ['blue'],
    // },
    // loft: {
    //     type: 'Mask',
    //     color: 'Loft',
    //     img: 'Loft.jpg',
    //     param: 'loft',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: true,
    //     tags: ['purple'],
    // },
    // sunset: {
    //     type: 'Mask',
    //     color: 'Sunset',
    //     img: 'Sunset.jpg',
    //     param: 'sunset',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: false,
    //     hot: true,
    //     tags: ['yellow', 'orange'],
    // },
    // whitedotted: {
    //     type: 'Mask',
    //     color: 'White Dotted',
    //     img: 'WhiteDotted.jpg',
    //     param: 'whitedotted',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['dots'],
    // },
    // flames: {
    //     type: 'Mask',
    //     color: 'Flames',
    //     img: 'Flames.jpg',
    //     param: 'flames',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['orange', 'yellow'],
    // },
    // sutra: {
    //     type: 'Mask',
    //     color: 'Sutra',
    //     img: 'Sutra.jpg',
    //     param: 'sutra',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'purple'],
    // },
    // cabin: {
    //     type: 'Mask',
    //     color: 'Cabin',
    //     img: 'Cabin.jpg',
    //     param: 'cabin',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     hot: false,
    //     tags: ['brown', 'white'],
    // },
    // buttercup: {
    //     type: 'Mask',
    //     color: 'Buttercup',
    //     img: 'Buttercup.jpg',
    //     param: 'buttercup',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     hot: false,
    //     tags: ['yellow', 'orange'],
    // },
    // blossom: {
    //     type: 'Mask',
    //     color: 'Blossom',
    //     img: 'Blossom.jpg',
    //     param: 'blossom',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'red'],
    // },
    // terrace: {
    //     type: 'Mask',
    //     color: 'Terrace',
    //     img: 'Terrace.jpg',
    //     param: 'terrace',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink'],
    // },
    // boyscout: {
    //     type: 'Mask',
    //     color: 'Boy Scout',
    //     img: 'BoyScout.jpg',
    //     param: 'boyscout',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'yellow'],
    // },
    // skulls: {
    //     type: 'Mask',
    //     color: 'Skulls',
    //     img: 'Skulls.jpg',
    //     param: 'skulls',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'orange'],
    // },
    // cherries: {
    //     type: 'Mask',
    //     color: 'Cherries',
    //     img: 'Cherries.jpg',
    //     param: 'cherries',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['green', 'red'],
    // },
    // floralgreen: {
    //     type: 'Mask',
    //     color: 'Floral Green',
    //     img: 'FloralGreen.jpg',
    //     param: 'floralgreen',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    // floralred: {
    //     type: 'Mask',
    //     color: 'Floral Red',
    //     img: 'FloralRed.jpg',
    //     param: 'floralred',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    // aroma: {
    //     type: 'Mask',
    //     color: 'Aroma',
    //     img: 'Aroma.jpg',
    //     param: 'aroma',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['red', 'yellow'],
    // },
    // stem: {
    //     type: 'Mask',
    //     color: 'Stem',
    //     img: 'Stem.jpg',
    //     param: 'stem',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['white', 'green'],
    // },
    // florallavender: {
    //     type: 'Mask',
    //     color: 'Floral Lavender',
    //     img: 'FloralLavender.jpg',
    //     param: 'florallavender',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'violet'],
    // },
    // floralpink: {
    //     type: 'Mask',
    //     color: 'Floral Pink',
    //     img: 'FloralPink.jpg',
    //     param: 'floralpink',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['red'],
    // },
    // gardener: {
    //     type: 'Mask',
    //     color: 'Gardener',
    //     img: 'Gardener.jpg',
    //     param: 'gardener',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['yellow'],
    // },
    // marinecorps: {
    //     type: 'Mask',
    //     color: 'Marine Corps',
    //     img: 'MarineCorps.jpg',
    //     param: 'marinecorps',
    //     price: maskPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // integrity: {
    //     type: 'Mask',
    //     color: 'Integrity',
    //     img: 'Integrity.jpg',
    //     param: 'integrity',
    //     price: maskPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // heels: {
    //     type: 'Mask',
    //     color: 'Heels',
    //     img: 'Heels.jpg',
    //     param: 'heels',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown', 'yellow'],
    // },
    // floralburgundy: {
    //     type: 'Mask',
    //     color: 'Floral Burgundy',
    //     img: 'FloralBurgundy.jpg',
    //     param: 'floralburgundy',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink', 'brown'],
    // },
    // classic: {
    //     type: 'Mask',
    //     color: 'Classic',
    //     img: 'Classic.jpg',
    //     param: 'classic',
    //     price: maskPrice,
    //     category: 'patriot',
    //     angled: false,
    //     tags: ['yellow', 'brown'],
    // },
    // buzz: {
    //     type: 'Mask',
    //     color: 'Buzz',
    //     img: 'Buzz.jpg',
    //     param: 'buzz',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['pink', 'yellow', 'bees'],
    // },
    // celeste: {
    //     type: 'Mask',
    //     color: 'Celeste',
    //     img: 'Celeste.jpg',
    //     param: 'celeste',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'brown'],
    // },
    // holly: {
    //     type: 'Mask',
    //     color: 'Holly',
    //     img: 'Holly.jpg',
    //     param: 'holly',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink', 'brown', 'burgundy'],
    // },
    // floralblue: {
    //     type: 'Mask',
    //     color: 'Floral Blue',
    //     img: 'FloralBlue.jpg',
    //     param: 'floralblue',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    // butterfly: {
    //     type: 'Mask',
    //     color: 'Butterfly',
    //     img: 'Butterfly.jpg',
    //     param: 'butterfly',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'purple', 'violet'],
    // },
    // fluorescent: {
    //     type: 'Mask',
    //     color: 'Fluorescent',
    //     img: 'Fluorescent.jpg',
    //     param: 'fluorescent',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'pink', 'purple'],
    // },
    // paradise: {
    //     type: 'Mask',
    //     color: 'Paradise',
    //     img: 'Paradise.jpg',
    //     param: 'paradise',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // royalty: {
    //     type: 'Mask',
    //     color: 'Royalty',
    //     img: 'Royalty.jpg',
    //     param: 'royalty',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'gold', 'yellow'],
    // },
    // daisy: {
    //     type: 'Mask',
    //     color: 'Daisy',
    //     img: 'Daisy.jpg',
    //     param: 'daisy',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    // corsage: {
    //     type: 'Mask',
    //     color: 'Corsage',
    //     img: 'Corsage.jpg',
    //     param: 'corsage',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'red', 'yellow'],
    // },
    // owl: {
    //     type: 'Mask',
    //     color: 'Owl',
    //     img: 'Owl.jpg',
    //     param: 'owl',
    //     price: maskPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // usguard: {
    //     type: 'Mask',
    //     color: 'US Guard',
    //     img: 'USGuard.jpg',
    //     param: 'usguard',
    //     price: maskPrice,
    //     category: 'patriot',
    //     angled: true,
    //     hot: false,
    //     tags: ['blue', 'grey'],
    // },
    // peaches: {
    //     type: 'Mask',
    //     color: 'Peaches',
    //     img: 'Peaches.jpg',
    //     param: 'peaches',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     hot: false,
    //     tags: ['pink', 'orange', 'red'],
    // },
    // swirl: {
    //     type: 'Mask',
    //     color: 'Swirl',
    //     img: 'Swirl.jpg',
    //     param: 'swirl',
    //     price: maskPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black'],
    // },
    // royal: {
    //     type: 'Mask',
    //     color: 'Royal',
    //     img: 'Royal.jpg',
    //     param: 'royal',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'gold', 'yellow'],
    // },
    // navygrey: {
    //     type: 'Mask',
    //     color: 'Navy Grey',
    //     img: 'NavyGrey.jpg',
    //     param: 'navygrey',
    //     price: maskPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // pineapple: {
    //     type: 'Mask',
    //     color: 'Pineapple',
    //     img: 'Pineapple.jpg',
    //     param: 'pineapple',
    //     price: maskPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['yellow'],
    // },
    // vines: {
    //     type: 'Mask',
    //     color: 'Vines',
    //     img: 'Vines.jpg',
    //     param: 'vines',
    //     price: maskPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green'],
    // },
};
