const setPrice = 40;

export const selection = {
    ////////////
    // SOLIDS //
    ///////////
    blackset: {
        type: 'Mask',
        color: 'Black',
        img: 'Black.jpg',
        param: 'black',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    darkgreyset: {
        type: 'Mask',
        color: 'Dark Grey',
        img: 'DarkGrey.jpg',
        param: 'darkgrey',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['black', 'white'],
    },
    greyset: {
        type: 'Mask',
        color: 'Grey',
        img: 'Grey.jpg',
        param: 'grey',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['black', 'white'],
    },
    ashset: {
        type: 'Mask',
        color: 'Ash',
        img: 'Ash.jpg',
        param: 'ash',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['black', 'grey'],
    },
    navyblueset: {
        type: 'Mask',
        color: 'Navy Blue',
        img: 'NavyBlue.jpg',
        param: 'navyblue',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    denimset: {
        type: 'Mask',
        color: 'Denim',
        img: 'Denim.jpg',
        param: 'denim',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['jeans', 'blue'],
    },
    pinkset: {
        type: 'Mask',
        color: 'Pink',
        img: 'Pink.jpg',
        param: 'pink',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['red'],
    },
    whiteset: {
        type: 'Mask',
        color: 'White',
        img: 'White.jpg',
        param: 'white',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    jumperset: {
        type: 'Mask',
        color: 'Jumper',
        img: 'Jumper.jpg',
        param: 'jumper',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['green'],
    },
    brownset: {
        type: 'Mask',
        color: 'Brown',
        img: 'Brown.jpg',
        param: 'brown',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    lavenderset: {
        type: 'Mask',
        color: 'Lavender',
        img: 'Lavender.jpg',
        param: 'lavender',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['purple', 'violet'],
    },
    greenset: {
        type: 'Mask',
        color: 'Green',
        img: 'Green.jpg',
        param: 'green',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    redset: {
        type: 'Mask',
        color: 'Red',
        img: 'Red.jpg',
        param: 'red',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['red', 'pink'],
    },
    orangeset: {
        type: 'Mask',
        color: 'Orange',
        img: 'Orange.jpg',
        param: 'orange',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['orange'],
    },
    yellowset: {
        type: 'Mask',
        color: 'Yellow',
        img: 'Yellow.jpg',
        param: 'yellow',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    peachset: {
        type: 'Mask',
        color: 'Peach',
        img: 'Peach.jpg',
        param: 'peach',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['orange'],
    },
    beigeset: {
        type: 'Mask',
        color: 'Beige',
        img: 'Beige.jpg',
        param: 'beige',
        price: setPrice,
        category: 'solid',
        angled: true,
        tags: ['orange', 'brown'],
    },
    //////////////
    // BANDANAS //
    /////////////
    blackbandanaset: {
        type: 'Mask',
        color: 'Black Bandana',
        img: 'BlackBandana.jpg',
        param: 'blackbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    navybandanaset: {
        type: 'Mask',
        color: 'Navy Bandana',
        img: 'NavyBandana.jpg',
        param: 'navybandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    royalbandanaset: {
        type: 'Mask',
        color: 'Royal Bandana',
        img: 'RoyalBandana.jpg',
        param: 'royalbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['navy'],
    },
    whitebandanaset: {
        type: 'Mask',
        color: 'White Bandana',
        img: 'WhiteBandana.jpg',
        param: 'whitebandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    redbandanaset: {
        type: 'Mask',
        color: 'Red Bandana',
        img: 'RedBandana.jpg',
        param: 'redbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['pink'],
    },
    pinkbandanaset: {
        type: 'Mask',
        color: 'Pink Bandana',
        img: 'PinkBandana.jpg',
        param: 'pinkbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['red'],
    },
    prodigalset: {
        type: 'Mask',
        color: 'Prodigal',
        img: 'Prodigal.jpg',
        param: 'prodigal',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    infinityset: {
        type: 'Mask',
        color: 'Infinity',
        img: 'Infinity.jpg',
        param: 'infinity',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['green', 'orange'],
    },
    reflectionset: {
        type: 'Mask',
        color: 'Reflection',
        img: 'Reflection.jpg',
        param: 'reflection',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    beyondset: {
        type: 'Mask',
        color: 'Beyond',
        img: 'Beyond.jpg',
        param: 'beyond',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    affinityset: {
        type: 'Mask',
        color: 'Affinity',
        img: 'Affinity.jpg',
        param: 'affinity',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['white'],
    },
    purplebandanaset: {
        type: 'Mask',
        color: 'Purple Bandana',
        img: 'PurpleBandana.jpg',
        param: 'purplebandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['purple', 'violet'],
    },
    eternityset: {
        type: 'Mask',
        color: 'Eternity',
        img: 'Eternity.jpg',
        param: 'eternity',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    sutraset: {
        type: 'Mask',
        color: 'Sutra',
        img: 'Sutra.jpg',
        param: 'sutra',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black', 'purple'],
    },
    creationset: {
        type: 'Mask',
        color: 'Creation',
        img: 'Creation.jpg',
        param: 'creation',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['green'],
    },
    orangebandanaset: {
        type: 'Mask',
        color: 'Orange Bandana',
        img: 'OrangeBandana.jpg',
        param: 'orangebandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['orange'],
    },
    yellowbandanaset: {
        type: 'Mask',
        color: 'Yellow Bandana',
        img: 'YellowBandana.jpg',
        param: 'yellowbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['yellow'],
    },
    greenbandanaset: {
        type: 'Mask',
        color: 'Green Bandana',
        img: 'GreenBandana.jpg',
        param: 'greenbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['green'],
    },
    limebandanaset: {
        type: 'Mask',
        color: 'Lime Bandana',
        img: 'LimeBandana.jpg',
        param: 'limebandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['green'],
    },
    skybandanaset: {
        type: 'Mask',
        color: 'Sky Bandana',
        img: 'SkyBandana.jpg',
        param: 'skybandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    brownbandanaset: {
        type: 'Mask',
        color: 'Brown Bandana',
        img: 'BrownBandana.jpg',
        param: 'brownbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown'],
    },
    beigebandanaset: {
        type: 'Mask',
        color: 'Beige Bandana',
        img: 'BeigeBandana.jpg',
        param: 'beigebandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown', 'beige'],
    },
    hibiscusbandanaset: {
        type: 'Mask',
        color: 'Hibiscus Bandana',
        img: 'HibiscusBandana.jpg',
        param: 'hibiscusbandana',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown', 'hibiscus'],
    },
    // bluebandanaset: {
    //     type: 'Mask',
    //     color: 'Blue Bandana',
    //     img: 'BlueBandana.jpg',
    //     param: 'bluebandana',
    //     price: maskPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['navy'],
    // },
    ///////////////
    // PATTERNED //
    //////////////
    navycamoset: {
        type: 'Mask',
        color: 'Navy Camo',
        img: 'NavyCamo.jpg',
        param: 'navycamo',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    armycamoset: {
        type: 'Mask',
        color: 'Army Camo',
        img: 'ArmyCamo.jpg',
        param: 'armycamo',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    camouflageset: {
        type: 'Mask',
        color: 'Camouflage',
        img: 'Camouflage.jpg',
        param: 'camouflage',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    graceset: {
        type: 'Mask',
        color: 'Grace',
        img: 'Grace.jpg',
        param: 'grace',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'yellow'],
    },
    hopeset: {
        type: 'Mask',
        color: 'Hope',
        img: 'Hope.jpg',
        param: 'hope',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'purple'],
    },
    superstarset: {
        type: 'Mask',
        color: 'Superstar',
        img: 'Superstar.jpg',
        param: 'superstar',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'colorful'],
    },
    starsset: {
        type: 'Mask',
        color: 'Stars',
        img: 'Stars.jpg',
        param: 'stars',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    dreamcatcherset: {
        type: 'Mask',
        color: 'Dreamcatcher',
        img: 'Dreamcatcher.jpg',
        param: 'dreamcatcher',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'red'],
    },
    snowflakeset: {
        type: 'Mask',
        color: 'Snowflake',
        img: 'Snowflake.jpg',
        param: 'snowflake',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    calaveraset: {
        type: 'Mask',
        color: 'Calavera',
        img: 'Calavera.jpg',
        param: 'calavera',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    moonlightset: {
        type: 'Mask',
        color: 'Moonlight',
        img: 'Moonlight.jpg',
        param: 'moonlight',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    zigzagset: {
        type: 'Mask',
        color: 'Zig Zag',
        img: 'ZigZag.jpg',
        param: 'zigzag',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    checkersset: {
        type: 'Mask',
        color: 'Checkers',
        img: 'Checkers.jpg',
        param: 'checkers',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    mortesset: {
        type: 'Mask',
        color: 'Mortes',
        img: 'Mortes.jpg',
        param: 'mortes',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    commandmentsset: {
        type: 'Mask',
        color: 'Commandments',
        img: 'Commandments.jpg',
        param: 'commandments',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'yellow', 'gold'],
    },
    rhombusset: {
        type: 'Mask',
        color: 'Rhombus',
        img: 'Rhombus.jpg',
        param: 'rhombus',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    minnieset: {
        type: 'Mask',
        color: 'Minnie',
        img: 'Minnie.jpg',
        param: 'minnie',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    reddottedset: {
        type: 'Mask',
        color: 'Red Dotted',
        img: 'RedDotted.jpg',
        param: 'reddotted',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    paisleyset: {
        type: 'Mask',
        color: 'Paisley',
        img: 'Paisley.jpg',
        param: 'paisley',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    artifactset: {
        type: 'Mask',
        color: 'Artifact',
        img: 'Artifact.jpg',
        param: 'artifact',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    artisanblackset: {
        type: 'Mask',
        color: 'Artisan Black',
        img: 'ArtisanBlack.jpg',
        param: 'artisanblack',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    kotaset: {
        type: 'Mask',
        color: 'Kota',
        img: 'Kota.jpg',
        param: 'kota',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    eveningset: {
        type: 'Mask',
        color: 'Evening',
        img: 'Evening.jpg',
        param: 'evening',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange', 'brown'],
    },
    butterflyset: {
        type: 'Mask',
        color: 'Butterfly',
        img: 'Butterfly.jpg',
        param: 'butterfly',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'purple'],
    },
    heartsset: {
        type: 'Mask',
        color: 'Hearts',
        img: 'Hearts.jpg',
        param: 'hearts',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    dazzleset: {
        type: 'Mask',
        color: 'Dazzle',
        img: 'Dazzle.jpg',
        param: 'dazzle',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    heiroset: {
        type: 'Mask',
        color: 'Heiro',
        img: 'Heiro.jpg',
        param: 'heiro',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    splashset: {
        type: 'Mask',
        color: 'Splash',
        img: 'Splash.jpg',
        param: 'splash',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow', 'orange'],
    },
    uniqueset: {
        type: 'Mask',
        color: 'Unique',
        img: 'Unique.jpg',
        param: 'unique',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'yellow'],
    },
    canvasset: {
        type: 'Mask',
        color: 'Canvas',
        img: 'Canvas.jpg',
        param: 'canvas',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    starpowerset: {
        type: 'Mask',
        color: 'Starpower',
        img: 'Starpower.jpg',
        param: 'starpower',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'pink', 'blue'],
    },
    swirlset: {
        type: 'Mask',
        color: 'Swirl',
        img: 'Swirl.jpg',
        param: 'swirl',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple'],
    },
    deepset: {
        type: 'Mask',
        color: 'Deep',
        img: 'Deep.jpg',
        param: 'deep',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple'],
    },
    illusionset: {
        type: 'Mask',
        color: 'Illusion',
        img: 'Illusion.jpg',
        param: 'illusion',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    ascendset: {
        type: 'Mask',
        color: 'Ascend',
        img: 'Ascend.jpg',
        param: 'ascend',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['white', 'blue'],
    },
    bubblegumset: {
        type: 'Mask',
        color: 'Bubblegum',
        img: 'Bubblegum.jpg',
        param: 'bubblegum',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    starspangledset: {
        type: 'Mask',
        color: 'Star Spangled',
        img: 'StarSpangled.jpg',
        param: 'starspangled',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'blue'],
    },
    artisticset: {
        type: 'Mask',
        color: 'Artistic',
        img: 'Artistic.jpg',
        param: 'artistic',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    universeset: {
        type: 'Mask',
        color: 'Universe',
        img: 'Universe.jpg',
        param: 'universe',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    galaxyset: {
        type: 'Mask',
        color: 'Galaxy',
        img: 'Galaxy.jpg',
        param: 'galaxy',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful', 'black'],
    },
    twineset: {
        type: 'Mask',
        color: 'Twine',
        img: 'Twine.jpg',
        param: 'twine',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink', 'red'],
    },
    signatureset: {
        type: 'Mask',
        color: 'Signature',
        img: 'Signature.jpg',
        param: 'signature',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    grandset: {
        type: 'Mask',
        color: 'Grand',
        img: 'Grand.jpg',
        param: 'grand',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    sparkleset: {
        type: 'Mask',
        color: 'Sparkle',
        img: 'Sparkle.jpg',
        param: 'sparkle',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    magneticset: {
        type: 'Mask',
        color: 'Magnetic',
        img: 'Magnetic.jpg',
        param: 'magnetic',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow', 'teal'],
    },
    radiantset: {
        type: 'Mask',
        color: 'Radiant',
        img: 'Radiant.jpg',
        param: 'radiant',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['yellow', 'orange', 'red'],
    },
    eraset: {
        type: 'Mask',
        color: 'Era',
        img: 'Era.jpg',
        param: 'era',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    flamesset: {
        type: 'Mask',
        color: 'Flames',
        img: 'Flames.jpg',
        param: 'flames',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['yellow', 'orange', 'red'],
    },
    nurseset: {
        type: 'Mask',
        color: 'Nurse',
        img: 'Nurse.jpg',
        param: 'nurse',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink', 'red'],
    },
    appleset: {
        type: 'Mask',
        color: 'Apple',
        img: 'Apple.jpg',
        param: 'apple',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    fancyset: {
        type: 'Mask',
        color: 'Fancy',
        img: 'Fancy.jpg',
        param: 'fancy',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'pink'],
    },
    ladybugset: {
        type: 'Mask',
        color: 'Ladybug',
        img: 'Ladybug.jpg',
        param: 'ladybug',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    blackdottedset: {
        type: 'Mask',
        color: 'Black Dotted',
        img: 'BlackDotted.jpg',
        param: 'blackdotted',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['dots'],
    },
    spotsset: {
        type: 'Mask',
        color: 'Spots',
        img: 'Spots.jpg',
        param: 'spots',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white', 'dots'],
    },
    polkset: {
        type: 'Mask',
        color: 'Polk',
        img: 'Polk.jpg',
        param: 'polk',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    polkadotsset: {
        type: 'Mask',
        color: 'Polkadots',
        img: 'Polkadots.jpg',
        param: 'polkadots',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['yellow'],
    },
    galaset: {
        type: 'Mask',
        color: 'Gala',
        img: 'Gala.jpg',
        param: 'gala',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'green', 'grey'],
    },
    soccerset: {
        type: 'Mask',
        color: 'Soccer',
        img: 'Soccer.jpg',
        param: 'soccer',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    carveset: {
        type: 'Mask',
        color: 'Carve',
        img: 'Carve.jpg',
        param: 'carve',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    walnutset: {
        type: 'Mask',
        color: 'Walnut',
        img: 'Walnut.jpg',
        param: 'walnut',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    rainbowset: {
        type: 'Mask',
        color: 'Rainbow',
        img: 'Rainbow.jpg',
        param: 'rainbow',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    stripeset: {
        type: 'Mask',
        color: 'Stripe',
        img: 'Stripe.jpg',
        param: 'stripe',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    plaidset: {
        type: 'Mask',
        color: 'Plaid',
        img: 'Plaid.jpg',
        param: 'plaid',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    tribalset: {
        type: 'Mask',
        color: 'Tribal',
        img: 'Tribal.jpg',
        param: 'tribal',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    redplaidset: {
        type: 'Mask',
        color: 'Red Plaid',
        img: 'RedPlaid.jpg',
        param: 'redplaid',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    enamorset: {
        type: 'Mask',
        color: 'Enamor',
        img: 'Enamor.jpg',
        param: 'enamor',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    menaceset: {
        type: 'Mask',
        color: 'Menace',
        img: 'Menace.jpg',
        param: 'menace',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    artisanredset: {
        type: 'Mask',
        color: 'Artisan Red',
        img: 'ArtisanRed.jpg',
        param: 'artisanred',
        price: setPrice,
        category: 'pattern',
        angled: false,
        tags: ['pink'],
    },
    musicset: {
        type: 'Mask',
        color: 'Music',
        img: 'Music.jpg',
        param: 'music',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    pianistset: {
        type: 'Mask',
        color: 'Pianist',
        img: 'Pianist.jpg',
        param: 'pianist',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    trumpetset: {
        type: 'Mask',
        color: 'Trumpet',
        img: 'Trumpet.jpg',
        param: 'trumpet',
        price: setPrice,
        category: 'pattern',
        angled: true,
        XLUnavailable: true,
        tags: ['orange'],
    },
    clarinetset: {
        type: 'Mask',
        color: 'Clarinet',
        img: 'Clarinet.jpg',
        param: 'clarinet',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    pinkcamoset: {
        type: 'Mask',
        color: 'Pink Camo',
        img: 'PinkCamo.jpg',
        param: 'pinkcamo',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    firefighterset: {
        type: 'Mask',
        color: 'Firefighter',
        img: 'Firefighter.jpg',
        param: 'firefighter',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    allureset: {
        type: 'Mask',
        color: 'Allure',
        img: 'Allure.jpg',
        param: 'allure',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'violet', 'lavender'],
    },
    motionset: {
        type: 'Mask',
        color: 'Motion',
        img: 'Motion.jpg',
        param: 'motion',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    nativeset: {
        type: 'Mask',
        color: 'Native',
        img: 'Native.jpg',
        param: 'native',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange', 'brown'],
    },
    lavandeset: {
        type: 'Mask',
        color: 'La Vandé',
        img: 'Lavande.jpg',
        param: 'lavande',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'pink'],
    },
    indusset: {
        type: 'Mask',
        color: 'Indus',
        img: 'Indus.jpg',
        param: 'indus',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'orange', 'teal'],
    },
    rezaset: {
        type: 'Mask',
        color: 'Reza',
        img: 'Reza.jpg',
        param: 'reza',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    ancientset: {
        type: 'Mask',
        color: 'Ancient',
        img: 'Ancient.jpg',
        param: 'ancient',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    arrowset: {
        type: 'Mask',
        color: 'Arrow',
        img: 'Arrow.jpg',
        param: 'arrow',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    shadesset: {
        type: 'Mask',
        color: 'Shades',
        img: 'Shades.jpg',
        param: 'shades',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    nightset: {
        type: 'Mask',
        color: 'Night',
        img: 'Night.jpg',
        param: 'night',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    woodsset: {
        type: 'Mask',
        color: 'Woods',
        img: 'Woods.jpg',
        param: 'woods',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'black', 'brown'],
    },
    winterset: {
        type: 'Mask',
        color: 'Winter',
        img: 'Winter.jpg',
        param: 'winter',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'blue', 'white'],
    },
    decorset: {
        type: 'Mask',
        color: 'Decor',
        img: 'Decor.jpg',
        param: 'decor',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['teal', 'orange', 'brown'],
    },
    geoset: {
        type: 'Mask',
        color: 'Geo',
        img: 'Geo.jpg',
        param: 'geo',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['teal', 'orange', 'brown'],
    },
    chevronsset: {
        type: 'Mask',
        color: 'Chevrons',
        img: 'Chevrons.jpg',
        param: 'chevrons',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    ////////////
    // ANIMAL //
    ///////////
    joyset: {
        type: 'Mask',
        color: 'Joy',
        img: 'Joy.jpg',
        param: 'joy',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    pawsset: {
        type: 'Mask',
        color: 'Paws',
        img: 'Paws.jpg',
        param: 'paws',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    lovableset: {
        type: 'Mask',
        color: 'Lovable',
        img: 'Lovable.jpg',
        param: 'lovable',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    pupperset: {
        type: 'Mask',
        color: 'Pupper',
        img: 'Pupper.jpg',
        param: 'pupper',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    doggieset: {
        type: 'Mask',
        color: 'Doggie',
        img: 'Doggie.jpg',
        param: 'doggie',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    sweetieset: {
        type: 'Mask',
        color: 'Sweetie',
        img: 'Sweetie.jpg',
        param: 'sweetie',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    tigerset: {
        type: 'Mask',
        color: 'Tiger',
        img: 'Tiger.jpg',
        param: 'tiger',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['orange'],
    },
    cheetahset: {
        type: 'Mask',
        color: 'Cheetah',
        img: 'Cheetah.jpg',
        param: 'cheetah',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'brown'],
    },
    snowleopardset: {
        type: 'Mask',
        color: 'Snow Leopard',
        img: 'SnowLeopard.jpg',
        param: 'snowleopard',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    spiritset: {
        type: 'Mask',
        color: 'Spirit',
        img: 'Spirit.jpg',
        param: 'spirit',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'blue', 'red'],
    },
    zebraset: {
        type: 'Mask',
        color: 'Zebra',
        img: 'Zebra.jpg',
        param: 'zebra',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'white'],
    },
    dalmationset: {
        type: 'Mask',
        color: 'Dalmation',
        img: 'Dalmation.jpg',
        param: 'dalmation',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    maldationset: {
        type: 'Mask',
        color: 'Maldation',
        img: 'Maldation.jpg',
        param: 'maldation',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    skipperset: {
        type: 'Mask',
        color: 'Skipper',
        img: 'Skipper.jpg',
        param: 'skipper',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['red'],
    },
    rawpset: {
        type: 'Mask',
        color: 'Rawp',
        img: 'Rawp.jpg',
        param: 'rawp',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs'],
    },
    happyset: {
        type: 'Mask',
        color: 'Happy',
        img: 'Happy.jpg',
        param: 'happy',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    bunniesset: {
        type: 'Mask',
        color: 'Bunnies',
        img: 'Bunnies.jpg',
        param: 'bunnies',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white'],
    },
    woofset: {
        type: 'Mask',
        color: 'Woof',
        img: 'Woof.jpg',
        param: 'woof',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'red'],
    },
    arfset: {
        type: 'Mask',
        color: 'Arf',
        img: 'Arf.jpg',
        param: 'arf',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'blue'],
    },
    underwaterset: {
        type: 'Mask',
        color: 'Underwater',
        img: 'Underwater.jpg',
        param: 'underwater',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    mermaidset: {
        type: 'Mask',
        color: 'Mermaid',
        img: 'Mermaid.jpg',
        param: 'mermaid',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    whaleset: {
        type: 'Mask',
        color: 'Whale',
        img: 'Whale.jpg',
        param: 'whale',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    jungleset: {
        type: 'Mask',
        color: 'Jungle',
        img: 'Jungle.jpg',
        param: 'jungle',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    unicornset: {
        type: 'Mask',
        color: 'Unicorn',
        img: 'Unicorn.jpg',
        param: 'unicorn',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    elephantset: {
        type: 'Mask',
        color: 'Elephant',
        img: 'Elephant.jpg',
        param: 'elephant',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    bearburyset: {
        type: 'Mask',
        color: 'Bearbury',
        img: 'Bearbury.jpg',
        param: 'bearbury',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    adorableset: {
        type: 'Mask',
        color: 'Adorable',
        img: 'Adorable.jpg',
        param: 'adorable',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['cats'],
    },
    kittensset: {
        type: 'Mask',
        color: 'Kittens',
        img: 'Kittens.jpg',
        param: 'kittens',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['cat', 'brown'],
    },
    dawgset: {
        type: 'Mask',
        color: 'Dawg',
        img: 'Dawg.jpg',
        param: 'dawg',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'brown'],
    },
    coolioset: {
        type: 'Mask',
        color: 'Coolio',
        img: 'Coolio.jpg',
        param: 'coolio',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    purrset: {
        type: 'Mask',
        color: 'Purr',
        img: 'Purr.jpg',
        param: 'purr',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['red', 'cats'],
    },
    meowset: {
        type: 'Mask',
        color: 'Meow',
        img: 'Meow.jpg',
        param: 'meow',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink', 'cats'],
    },
    cuteset: {
        type: 'Mask',
        color: 'Cute',
        img: 'Cute.jpg',
        param: 'cute',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'cat', 'navy'],
    },
    xrayset: {
        type: 'Mask',
        color: 'X-Ray',
        img: 'X-Ray.jpg',
        param: 'xray',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'cat', 'navy'],
    },
    milkset: {
        type: 'Mask',
        color: 'Milk',
        img: 'Milk.jpg',
        param: 'milk',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    mooset: {
        type: 'Mask',
        color: 'Moo',
        img: 'Moo.jpg',
        param: 'moo',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey', 'black'],
    },
    jaguarset: {
        type: 'Mask',
        color: 'Jaguar',
        img: 'Jaguar.jpg',
        param: 'jaguar',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    rooset: {
        type: 'Mask',
        color: 'Roo',
        img: 'Roo.jpg',
        param: 'roo',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    hunterset: {
        type: 'Mask',
        color: 'Hunter',
        img: 'Hunter.jpg',
        param: 'hunter',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    featherset: {
        type: 'Mask',
        color: 'Feather',
        img: 'Feather.jpg',
        param: 'feather',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'grey'],
    },
    flamingoset: {
        type: 'Mask',
        color: 'Flamingo',
        img: 'Flamingo.jpg',
        param: 'flamingo',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'orange'],
    },
    blackandwhiteset: {
        type: 'Mask',
        color: 'Black & White',
        img: 'Black&White.jpg',
        param: 'blackandwhite',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'white'],
    },
    pandaset: {
        type: 'Mask',
        color: 'Panda',
        img: 'Panda.jpg',
        param: 'panda',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey'],
    },
    ranchset: {
        type: 'Mask',
        color: 'Ranch',
        img: 'Ranch.jpg',
        param: 'ranch',
        price: setPrice,
        category: 'animal',
        angled: true,

        tags: ['grey'],
    },
    violetredzebraset: {
        type: 'Mask',
        color: 'Violet Red Zebra',
        img: 'VioletRedZebra.jpg',
        param: 'violetredzebra',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['purple', 'magenta'],
    },
    cobraset: {
        type: 'Mask',
        color: 'Cobra',
        img: 'Cobra.jpg',
        param: 'cobra',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'orange', 'brown'],
    },
    snakeskinset: {
        type: 'Mask',
        color: 'Snakeskin',
        img: 'Snakeskin.jpg',
        param: 'snakeskin',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'orange', 'brown'],
    },
    playset: {
        type: 'Mask',
        color: 'Play',
        img: 'Play.jpg',
        param: 'play',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'red'],
    },
    eagleset: {
        type: 'Mask',
        color: 'Eagle',
        img: 'Eagle.jpg',
        param: 'eagle',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'bird'],
    },
    owlsset: {
        type: 'Mask',
        color: 'Owls',
        img: 'Owls.jpg',
        param: 'owls',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    owliesset: {
        type: 'Mask',
        color: 'Owlies',
        img: 'Owlies.jpg',
        param: 'owlies',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey'],
    },
    madagascarset: {
        type: 'Mask',
        color: 'Madagascar',
        img: 'Madagascar.jpg',
        param: 'madagascar',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    parrotsset: {
        type: 'Mask',
        color: 'Parrots',
        img: 'Parrots.jpg',
        param: 'parrots',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['bird', 'colorful'],
    },
    toucanset: {
        type: 'Mask',
        color: 'Toucan',
        img: 'Toucan.jpg',
        param: 'toucan',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['bird', 'black'],
    },
    furrballsset: {
        type: 'Mask',
        color: 'Furrballs',
        img: 'Furrballs.jpg',
        param: 'furrballs',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['cats'],
    },
    poochset: {
        type: 'Mask',
        color: 'Pooch',
        img: 'Pooch.jpg',
        param: 'pooch',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs'],
    },
    kennelset: {
        type: 'Mask',
        color: 'Kennel',
        img: 'Kennel.jpg',
        param: 'kennel',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs', 'brown'],
    },
    barkinglotset: {
        type: 'Mask',
        color: 'Barking Lot',
        img: 'BarkingLot.jpg',
        param: 'barkinglot',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs', 'brown'],
    },
    llamaset: {
        type: 'Mask',
        color: 'Llama',
        img: 'Llama.jpg',
        param: 'llama',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    arcticset: {
        type: 'Mask',
        color: 'Arctic',
        img: 'Arctic.jpg',
        param: 'arctic',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    seahorseset: {
        type: 'Mask',
        color: 'Seahorse',
        img: 'Seahorse.jpg',
        param: 'seahorse',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    penguinsset: {
        type: 'Mask',
        color: 'Penguins',
        img: 'Penguins.jpg',
        param: 'penguins',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'grey', 'blue'],
    },
    dreamyset: {
        type: 'Mask',
        color: 'Dreamy',
        img: 'Dreamy.jpg',
        param: 'dreamy',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    dinoset: {
        type: 'Mask',
        color: 'Dino',
        img: 'Dino.jpg',
        param: 'dino',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    //////////////
    // HAWAIIAN //
    //////////////
    hulaset: {
        type: 'Mask',
        color: 'Hula',
        img: 'Hula.jpg',
        param: 'hula',
        price: setPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['pink', 'red', 'green'],
    },
    pondset: {
        type: 'Mask',
        color: 'Pond',
        img: 'Pond.jpg',
        param: 'pond',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    suaveset: {
        type: 'Mask',
        color: 'Suave',
        img: 'Suave.jpg',
        param: 'suave',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['grey'],
    },
    palmsset: {
        type: 'Mask',
        color: 'Palms',
        img: 'Palms.jpg',
        param: 'palms',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['black'],
    },
    koiset: {
        type: 'Mask',
        color: 'Koi',
        img: 'Koi.jpg',
        param: 'koi',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    sunsetset: {
        type: 'Mask',
        color: 'Sunset',
        img: 'Sunset.jpg',
        param: 'sunset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    skyset: {
        type: 'Mask',
        color: 'Sky',
        img: 'Sky.jpg',
        param: 'sky',
        price: setPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['blue'],
    },
    alohaset: {
        type: 'Mask',
        color: 'Aloha',
        img: 'Aloha.jpg',
        param: 'aloha',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'orange', 'yellow'],
    },
    glowset: {
        type: 'Mask',
        color: 'Glow',
        img: 'Glow.jpg',
        param: 'glow',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    canopyset: {
        type: 'Mask',
        color: 'Canopy',
        img: 'Canopy.jpg',
        param: 'canopy',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['pink', 'green'],
    },
    duskset: {
        type: 'Mask',
        color: 'Dusk',
        img: 'Dusk.jpg',
        param: 'dusk',
        price: setPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['pink'],
    },
    surfset: {
        type: 'Mask',
        color: 'Surf',
        img: 'Surf.jpg',
        param: 'surf',
        price: setPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['grey', 'yellow'],
    },
    honoluluset: {
        type: 'Mask',
        color: 'Honolulu',
        img: 'Honolulu.jpg',
        param: 'honolulu',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red'],
    },
    ////////////
    // FLORAL //
    ////////////,
    elegantset: {
        type: 'Mask',
        color: 'Elegant',
        img: 'Elegant.jpg',
        param: 'elegant',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    divineset: {
        type: 'Mask',
        color: 'Divine',
        img: 'Divine.jpg',
        param: 'divine',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    fragrantset: {
        type: 'Mask',
        color: 'Fragrant',
        img: 'Fragrant.jpg',
        param: 'fragrant',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    charmset: {
        type: 'Mask',
        color: 'Charm',
        img: 'Charm.jpg',
        param: 'charm',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    vibrantset: {
        type: 'Mask',
        color: 'Vibrant',
        img: 'Vibrant.jpg',
        param: 'vibrant',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'blue'],
    },
    sereneset: {
        type: 'Mask',
        color: 'Serene',
        img: 'Serene.jpg',
        param: 'serene',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black'],
    },
    bouquetset: {
        type: 'Mask',
        color: 'Bouquet',
        img: 'Bouquet.jpg',
        param: 'bouquet',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'purple'],
    },
    lunaset: {
        type: 'Mask',
        color: 'Luna',
        img: 'Luna.jpg',
        param: 'luna',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    crystallisset: {
        type: 'Mask',
        color: 'Crystallis',
        img: 'Crystallis.jpg',
        param: 'crystallis',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'black'],
    },
    amethystset: {
        type: 'Mask',
        color: 'Amethyst',
        img: 'Amethyst.jpg',
        param: 'amethyst',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    glistenset: {
        type: 'Mask',
        color: 'Glisten',
        img: 'Glisten.jpg',
        param: 'glisten',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    growthset: {
        type: 'Mask',
        color: 'Growth',
        img: 'Growth.jpg',
        param: 'growth',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'blue'],
    },
    maroonaset: {
        type: 'Mask',
        color: 'Maroona',
        img: 'Maroona.jpg',
        param: 'maroona',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['maroon', 'red'],
    },
    curaset: {
        type: 'Mask',
        color: 'Cura',
        img: 'Cura.jpg',
        param: 'cura',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['maroon', 'red'],
    },
    wondrousset: {
        type: 'Mask',
        color: 'Wondrous',
        img: 'Wondrous.jpg',
        param: 'wondrous',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    aretiaset: {
        type: 'Mask',
        color: 'Aretia',
        img: 'Aretia.jpg',
        param: 'aretia',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'gold'],
    },
    beautyset: {
        type: 'Mask',
        color: 'Beauty',
        img: 'Beauty.jpg',
        param: 'beauty',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    exquisiteset: {
        type: 'Mask',
        color: 'Exquisite',
        img: 'Exquisite.jpg',
        param: 'exquisite',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    splendidset: {
        type: 'Mask',
        color: 'Splendid',
        img: 'Splendid.jpg',
        param: 'splendid',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    luckset: {
        type: 'Mask',
        color: 'Luck',
        img: 'Luck.jpg',
        param: 'luck',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    passionset: {
        type: 'Mask',
        color: 'Passion',
        img: 'Passion.jpg',
        param: 'passion',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    luxuriousset: {
        type: 'Mask',
        color: 'Luxurious',
        img: 'Luxurious.jpg',
        param: 'luxurious',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    miracleset: {
        type: 'Mask',
        color: 'Miracle',
        img: 'Miracle.jpg',
        param: 'miracle',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'pink'],
    },
    marvelset: {
        type: 'Mask',
        color: 'Marvel',
        img: 'Marvel.jpg',
        param: 'marvel',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    sunlightset: {
        type: 'Mask',
        color: 'Sunlight',
        img: 'Sunlight.jpg',
        param: 'sunlight',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['orange'],
    },
    delightset: {
        type: 'Mask',
        color: 'Delight',
        img: 'Delight.jpg',
        param: 'delight',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white'],
    },
    ornateset: {
        type: 'Mask',
        color: 'Ornate',
        img: 'Ornate.jpg',
        param: 'ornate',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    swellset: {
        type: 'Mask',
        color: 'Swell',
        img: 'Swell.jpg',
        param: 'swell',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    enchantingset: {
        type: 'Mask',
        color: 'Enchanting',
        img: 'Enchanting.jpg',
        param: 'enchanting',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    flourishset: {
        type: 'Mask',
        color: 'Flourish',
        img: 'Flourish.jpg',
        param: 'flourish',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    majesticset: {
        type: 'Mask',
        color: 'Majestic',
        img: 'Majestic.jpg',
        param: 'majestic',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red', 'yellow'],
    },
    lovelyset: {
        type: 'Mask',
        color: 'Lovely',
        img: 'Lovely.jpg',
        param: 'lovely',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    pureset: {
        type: 'Mask',
        color: 'Pure',
        img: 'Pure.jpg',
        param: 'pure',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    clarityset: {
        type: 'Mask',
        color: 'Clarity',
        img: 'Clarity.jpg',
        param: 'clarity',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    silvermoonset: {
        type: 'Mask',
        color: 'Silvermoon',
        img: 'Silvermoon.jpg',
        param: 'silvermoon',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'silver'],
    },
    exuberantset: {
        type: 'Mask',
        color: 'Exuberant',
        img: 'Exuberant.jpg',
        param: 'exuberant',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    heavenlyset: {
        type: 'Mask',
        color: 'Heavenly',
        img: 'Heavenly.jpg',
        param: 'heavenly',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    affectionset: {
        type: 'Mask',
        color: 'Affection',
        img: 'Affection.jpg',
        param: 'affection',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    sapphireset: {
        type: 'Mask',
        color: 'Sapphire',
        img: 'Sapphire.jpg',
        param: 'sapphire',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    rubyset: {
        type: 'Mask',
        color: 'Ruby',
        img: 'Ruby.jpg',
        param: 'ruby',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    preciousset: {
        type: 'Mask',
        color: 'Precious',
        img: 'Precious.jpg',
        param: 'precious',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    antiqueset: {
        type: 'Mask',
        color: 'Antique',
        img: 'Antique.jpg',
        param: 'antique',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    naturalset: {
        type: 'Mask',
        color: 'Natural',
        img: 'Natural.jpg',
        param: 'natural',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow'],
    },
    honeyset: {
        type: 'Mask',
        color: 'Honey',
        img: 'Honey.jpg',
        param: 'honey',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'yellow'],
    },
    tranquilset: {
        type: 'Mask',
        color: 'Tranquil',
        img: 'Tranquil.jpg',
        param: 'tranquil',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red', 'blue'],
    },
    bloomset: {
        type: 'Mask',
        color: 'Bloom',
        img: 'Bloom.jpg',
        param: 'bloom',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    bubblyset: {
        type: 'Mask',
        color: 'Bubbly',
        img: 'Bubbly.jpg',
        param: 'bubbly',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    pleasantriesset: {
        type: 'Mask',
        color: 'Pleasantries',
        img: 'Pleasantries.jpg',
        param: 'pleasantries',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'beige', 'brown'],
    },
    brightset: {
        type: 'Mask',
        color: 'Bright',
        img: 'Bright.jpg',
        param: 'bright',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [''],
    },
    blossomset: {
        type: 'Mask',
        color: 'Blossom',
        img: 'Blossom.jpg',
        param: 'blossom',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    harvestset: {
        type: 'Mask',
        color: 'Harvest',
        img: 'Harvest.jpg',
        param: 'harvest',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'orange'],
    },
    adoreset: {
        type: 'Mask',
        color: 'Adore',
        img: 'Adore.jpg',
        param: 'adore',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'pink'],
    },
    blissset: {
        type: 'Mask',
        color: 'Bliss',
        img: 'Bliss.jpg',
        param: 'bliss',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'purple'],
    },
    thriveset: {
        type: 'Mask',
        color: 'Thrive',
        img: 'Thrive.jpg',
        param: 'thrive',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'pink'],
    },
    flatterset: {
        type: 'Mask',
        color: 'Flatter',
        img: 'Flatter.jpg',
        param: 'flatter',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'yellow'],
    },
    vividset: {
        type: 'Mask',
        color: 'Vivid',
        img: 'Vivid.jpg',
        param: 'vivid',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple'],
    },
    zenset: {
        type: 'Mask',
        color: 'Zen',
        img: 'Zen.jpg',
        param: 'zen',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    captivateset: {
        type: 'Mask',
        color: 'Captivate',
        img: 'Captivate.jpg',
        param: 'captivate',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'yellow'],
    },
    cherishset: {
        type: 'Mask',
        color: 'Cherish',
        img: 'Cherish.jpg',
        param: 'cherish',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'orange'],
    },
    rosesset: {
        type: 'Mask',
        color: 'Roses',
        img: 'Roses.jpg',
        param: 'roses',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    prettyset: {
        type: 'Mask',
        color: 'Pretty',
        img: 'Pretty.jpg',
        param: 'pretty',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'blue'],
    },
    floretset: {
        type: 'Mask',
        color: 'Floret',
        img: 'Floret.jpg',
        param: 'floret',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'pink', 'purple'],
    },
    harmonyset: {
        type: 'Mask',
        color: 'Harmony',
        img: 'Harmony.jpg',
        param: 'harmony',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    gardenset: {
        type: 'Mask',
        color: 'Garden',
        img: 'Garden.jpg',
        param: 'garden',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    bountifulset: {
        type: 'Mask',
        color: 'Bountiful',
        img: 'Bountiful.jpg',
        param: 'bountiful',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow'],
    },
    opalset: {
        type: 'Mask',
        color: 'Opal',
        img: 'Opal.jpg',
        param: 'opal',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    springset: {
        type: 'Mask',
        color: 'Spring',
        img: 'Spring.jpg',
        param: 'spring',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink', 'blue'],
    },
    buoyantset: {
        type: 'Mask',
        color: 'Buoyant',
        img: 'Buoyant.jpg',
        param: 'buoyant',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    cultivateset: {
        type: 'Mask',
        color: 'Cultivate',
        img: 'Cultivate.jpg',
        param: 'cultivate',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'orange', 'red'],
    },
    treasureset: {
        type: 'Mask',
        color: 'Treasure',
        img: 'Treasure.jpg',
        param: 'treasure',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    perfumeset: {
        type: 'Mask',
        color: 'Perfume',
        img: 'Perfume.jpg',
        param: 'perfume',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet', 'lavender'],
    },
    parfumset: {
        type: 'Mask',
        color: 'Parfum',
        img: 'Parfum.jpg',
        param: 'parfum',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    coralset: {
        type: 'Mask',
        color: 'Coral',
        img: 'Coral.jpg',
        param: 'coral',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'purple'],
    },
    magnificentset: {
        type: 'Mask',
        color: 'Magnificent',
        img: 'Magnificent.jpg',
        param: 'magnificent',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    meadowset: {
        type: 'Mask',
        color: 'Meadow',
        img: 'Meadow.jpg',
        param: 'meadow',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow', 'orange', 'blue'],
    },
    sunshineset: {
        type: 'Mask',
        color: 'Sunshine',
        img: 'Sunshine.jpg',
        param: 'sunshine',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue', 'yellow', 'red'],
    },
    beamingset: {
        type: 'Mask',
        color: 'Beaming',
        img: 'Beaming.jpg',
        param: 'beaming',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'orange'],
    },
    floralwhiteset: {
        type: 'Mask',
        color: 'Floral White',
        img: 'FloralWhite.jpg',
        param: 'floralwhite',
        price: setPrice,
        category: 'floral',
        angled: false,
        tags: [],
    },
    purpleplaidset: {
        type: 'Mask',
        color: 'Purple Plaid',
        img: 'PurplePlaid.jpg',
        param: 'purpleplaid',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['lavender', 'violet'],
    },
    orangeplaidset: {
        type: 'Mask',
        color: 'Orange Plaid',
        img: 'OrangePlaid.jpg',
        param: 'orangeplaid',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    hempset: {
        type: 'Mask',
        color: 'Hemp',
        img: 'Hemp.jpg',
        param: 'hemp',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    stunningset: {
        type: 'Mask',
        color: 'Stunning',
        img: 'Stunning.jpg',
        param: 'stunning',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    fairytaleset: {
        type: 'Mask',
        color: 'Fairytale',
        img: 'Fairytale.jpg',
        param: 'fairytale',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'pink'],
    },
    //////////////
    // MEMORIAL //
    //////////////
    usaset: {
        type: 'Mask',
        color: 'USA',
        img: 'USA.jpg',
        param: 'usa',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    americanset: {
        type: 'Mask',
        color: 'American',
        img: 'American.jpg',
        param: 'american',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    patriotset: {
        type: 'Mask',
        color: 'Patriot',
        img: 'Patriot.jpg',
        param: 'patriot',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    classicset: {
        type: 'Mask',
        color: 'Classic',
        img: 'Classic.jpg',
        param: 'classic',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    nationalset: {
        type: 'Mask',
        color: 'National',
        img: 'National.jpg',
        param: 'national',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    libertyset: {
        type: 'Mask',
        color: 'Liberty',
        img: 'Liberty.jpg',
        param: 'liberty',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    gloryset: {
        type: 'Mask',
        color: 'Glory',
        img: 'Glory.jpg',
        param: 'glory',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['black'],
    },
    serviceset: {
        type: 'Mask',
        color: 'Service',
        img: 'Service.jpg',
        param: 'service',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    airforceset: {
        type: 'Mask',
        color: 'United',
        img: 'AirForce.jpg',
        param: 'airforce',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown', 'army'],
    },
    marinesset: {
        type: 'Mask',
        color: 'Marines',
        img: 'Marines.jpg',
        param: 'marines',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown', 'army'],
    },
    usnavyset: {
        type: 'Mask',
        color: 'US Navy',
        img: 'USNavy.jpg',
        param: 'usnavy',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    armyset: {
        type: 'Mask',
        color: 'Army',
        img: 'Army.jpg',
        param: 'army',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    excellenceset: {
        type: 'Mask',
        color: 'Excellence',
        img: 'Excellence.jpg',
        param: 'excellence',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    veteranset: {
        type: 'Mask',
        color: 'Veteran',
        img: 'Veteran.jpg',
        param: 'veteran',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown'],
    },
    forcesset: {
        type: 'Mask',
        color: 'Forces',
        img: 'Forces.jpg',
        param: 'forces',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    saluteset: {
        type: 'Mask',
        color: 'Salute',
        img: 'Salute.jpg',
        param: 'salute',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    tagsset: {
        type: 'Mask',
        color: 'Tags',
        img: 'Tags.jpg',
        param: 'tags',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['black'],
    },
    ////////////
    // HOLIDAY //
    ////////////
    spookyset: {
        type: 'Mask',
        color: 'Spooky',
        img: 'Spooky.jpg',
        param: 'spooky',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    booset: {
        type: 'Mask',
        color: 'Boo',
        img: 'Boo.jpg',
        param: 'boo',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    crawlerset: {
        type: 'Mask',
        color: 'Crawler',
        img: 'Crawler.jpg',
        param: 'crawler',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    mistletoeset: {
        type: 'Mask',
        color: 'Mistletoe',
        img: 'Mistletoe.jpg',
        param: 'mistletoe',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    poinsettiaset: {
        type: 'Mask',
        color: 'Poinsettia',
        img: 'Poinsettia.jpg',
        param: 'poinsettia',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    cheersset: {
        type: 'Mask',
        color: 'Cheers',
        img: 'Cheers.jpg',
        param: 'cheers',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    santaset: {
        type: 'Mask',
        color: 'Santa',
        img: 'Santa.jpg',
        param: 'santa',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    merryset: {
        type: 'Mask',
        color: 'Merry',
        img: 'Merry.jpg',
        param: 'merry',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    snowmanset: {
        type: 'Mask',
        color: 'Snowman',
        img: 'Snowman.jpg',
        param: 'snowman',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    shinglesset: {
        type: 'Mask',
        color: 'Shingles',
        img: 'Shingles.jpg',
        param: 'shingles',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    frostyset: {
        type: 'Mask',
        color: 'Frosty',
        img: 'Frosty.jpg',
        param: 'frosty',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    reindeerset: {
        type: 'Mask',
        color: 'Reindeer',
        img: 'Reindeer.jpg',
        param: 'reindeer',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    jinglebellsset: {
        type: 'Mask',
        color: 'Jingle Bells',
        img: 'JingleBells.jpg',
        param: 'jinglebells',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    merryplaidset: {
        type: 'Mask',
        color: 'Merry Plaid',
        img: 'MerryPlaid.jpg',
        param: 'merryplaid',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    swanset: {
        type: 'Mask',
        color: 'Swan',
        img: 'Swan.jpg',
        param: 'swan',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
    snowyset: {
        type: 'Mask',
        color: 'Snowy',
        img: 'Snowy.jpg',
        param: 'snowy',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    fortuneset: {
        type: 'Mask',
        color: 'Fortune',
        img: 'Fortune.jpg',
        param: 'fortune',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    angelicset: {
        type: 'Mask',
        color: 'Angelic',
        img: 'Angelic.jpg',
        param: 'angelic',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    jovialset: {
        type: 'Mask',
        color: 'Jovial',
        img: 'Jovial.jpg',
        param: 'jovial',
        price: setPrice,
        category: 'pattern',
        angled: false,
        tags: [''],
    },
    pineappleset: {
        type: 'Mask',
        color: 'Pineapple',
        img: 'Pineapple.jpg',
        param: 'pineapple',
        price: setPrice,
        category: 'pattern',
        angled: false,
        tags: [''],
    },
    redpolkadotset: {
        type: 'Mask',
        color: 'Red Polkadot',
        img: 'RedPolkadot.jpg',
        param: 'redpolkadot',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    greypolkadotset: {
        type: 'Mask',
        color: 'Grey Polkadot',
        img: 'GreyPolkadot.jpg',
        param: 'greypolkadot',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    giftsset: {
        type: 'Mask',
        color: 'Gifts',
        img: 'Gifts.jpg',
        param: 'gifts',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    flamingodanceset: {
        type: 'Mask',
        color: 'Flamingo Dance',
        img: 'FlamingoDance.jpg',
        param: 'flamingodance',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
    choirset: {
        type: 'Mask',
        color: 'Choir',
        img: 'Choir.jpg',
        param: 'choir',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    christmasset: {
        type: 'Mask',
        color: 'Christmas',
        img: 'Christmas.jpg',
        param: 'christmas',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    ornamentset: {
        type: 'Mask',
        color: 'Ornament',
        img: 'Ornament.jpg',
        param: 'ornament',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    rosemaryset: {
        type: 'Mask',
        color: 'Rosemary',
        img: 'Rosemary.jpg',
        param: 'rosemary',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
};
