const setPrice = 40;
export const waistBagPrice = 15;

export const selection = {
    ////////////
    // SOLIDS //
    ///////////
    // blackset: {
    //     type: 'Bag',
    //     color: 'Black',
    //     img: 'Black.jpg',
    //     param: 'black',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: [],
    // },
    // darkgreyset: {
    //     type: 'Bag',
    //     color: 'Dark Grey',
    //     img: 'DarkGrey.jpg',
    //     param: 'darkgrey',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // greyset: {
    //     type: 'Bag',
    //     color: 'Grey',
    //     img: 'Grey.jpg',
    //     param: 'grey',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // ashset: {
    //     type: 'Bag',
    //     color: 'Ash',
    //     img: 'Ash.jpg',
    //     param: 'ash',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['black', 'grey'],
    // },
    // navyblueset: {
    //     type: 'Bag',
    //     color: 'Navy Blue',
    //     img: 'NavyBlue.jpg',
    //     param: 'navyblue',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: [],
    // },
    denimset: {
        type: 'Bag',
        color: 'Denim Set',
        img: 'DenimSet.jpg',
        param: 'denimset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['jeans', 'blue'],
    },
    // pinkset: {
    //     type: 'Bag',
    //     color: 'Pink',
    //     img: 'Pink.jpg',
    //     param: 'pink',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['red'],
    // },
    // whiteset: {
    //     type: 'Bag',
    //     color: 'White',
    //     img: 'White.jpg',
    //     param: 'white',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: [],
    // },
    // jumperset: {
    //     type: 'Bag',
    //     color: 'Jumper',
    //     img: 'Jumper.jpg',
    //     param: 'jumper',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['green'],
    // },
    // brownset: {
    //     type: 'Bag',
    //     color: 'Brown',
    //     img: 'Brown.jpg',
    //     param: 'brown',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: [],
    // },
    // lavenderset: {
    //     type: 'Bag',
    //     color: 'Lavender',
    //     img: 'Lavender.jpg',
    //     param: 'lavender',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['purple', 'violet'],
    // },
    // greenset: {
    //     type: 'Bag',
    //     color: 'Green',
    //     img: 'Green.jpg',
    //     param: 'green',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: [],
    // },
    // redset: {
    //     type: 'Bag',
    //     color: 'Red',
    //     img: 'Red.jpg',
    //     param: 'red',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['red', 'pink'],
    // },
    // orangeset: {
    //     type: 'Bag',
    //     color: 'Orange',
    //     img: 'Orange.jpg',
    //     param: 'orange',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['orange'],
    // },
    // yellowset: {
    //     type: 'Bag',
    //     color: 'Yellow',
    //     img: 'Yellow.jpg',
    //     param: 'yellow',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: [],
    // },
    // peachset: {
    //     type: 'Bag',
    //     color: 'Peach',
    //     img: 'Peach.jpg',
    //     param: 'peach',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['orange'],
    // },
    // beigeset: {
    //     type: 'Bag',
    //     color: 'Beige',
    //     img: 'Beige.jpg',
    //     param: 'beige',
    //     price: setPrice,
    //     category: 'solid',
    //     angled: true,
    //     tags: ['orange', 'brown'],
    // },
    // //////////////
    // // BANDANAS //
    // /////////////
    blackbandanaset: {
        type: 'Bag',
        color: 'Black Bandana Set',
        img: 'BlackBandanaSet.jpg',
        param: 'blackbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    navybandanaset: {
        type: 'Bag',
        color: 'Navy Bandana Set',
        img: 'NavyBandanaSet.jpg',
        param: 'navybandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    // royalbandanaset: {
    //     type: 'Bag',
    //     color: 'Royal Bandana',
    //     img: 'RoyalBandana.jpg',
    //     param: 'royalbandana',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['navy'],
    // },
    whitebandanaset: {
        type: 'Bag',
        color: 'White Bandana Set',
        img: 'WhiteBandanaSet.jpg',
        param: 'whitebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    redbandanaset: {
        type: 'Bag',
        color: 'Red Bandana Set',
        img: 'RedBandanaSet.jpg',
        param: 'redbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['pink'],
    },
    pinkbandanaset: {
        type: 'Bag',
        color: 'Pink Bandana Set',
        img: 'PinkBandanaSet.jpg',
        param: 'pinkbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['red'],
    },
    darkbandanaset: {
        type: 'Bag',
        color: 'Dark Bandana Set',
        img: 'DarkBandanaSet.jpg',
        param: 'darkbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    prodigalset: {
        type: 'Bag',
        color: 'Prodigal Set',
        img: 'ProdigalSet.jpg',
        param: 'prodigalset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    silvaset: {
        type: 'Bag',
        color: 'Silva Set',
        img: 'SilvaSet.jpg',
        param: 'silvaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    prosperityset: {
        type: 'Bag',
        color: 'Prosperity Set',
        img: 'ProsperitySet.jpg',
        param: 'prosperityset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    expressionset: {
        type: 'Bag',
        color: 'Expression Set',
        img: 'ExpressionSet.jpg',
        param: 'expressionset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    infinityset: {
        type: 'Bag',
        color: 'Infinity Set',
        img: 'InfinitySet.jpg',
        param: 'infinityset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['green', 'orange'],
    },
    // reflectionset: {
    //     type: 'Bag',
    //     color: 'Reflection',
    //     img: 'Reflection.jpg',
    //     param: 'reflection',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['blue'],
    // },
    beyondset: {
        type: 'Bag',
        color: 'Beyond Set',
        img: 'BeyondSet.jpg',
        param: 'beyondset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    affinityset: {
        type: 'Bag',
        color: 'Affinity Set',
        img: 'AffinitySet.jpg',
        param: 'affinityset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['white'],
    },
    purplebandanaset: {
        type: 'Bag',
        color: 'Purple Bandana Set',
        img: 'PurpleBandanaSet.jpg',
        param: 'purplebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['purple', 'violet'],
    },
    innerset: {
        type: 'Bag',
        color: 'Inner Set',
        img: 'InnerSet.jpg',
        param: 'innerset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    // eternityset: {
    //     type: 'Bag',
    //     color: 'Eternity',
    //     img: 'Eternity.jpg',
    //     param: 'eternity',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['black'],
    // },
    // sutraset: {
    //     type: 'Bag',
    //     color: 'Sutra',
    //     img: 'Sutra.jpg',
    //     param: 'sutra',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['black', 'purple'],
    // },
    // creationset: {
    //     type: 'Bag',
    //     color: 'Creation',
    //     img: 'Creation.jpg',
    //     param: 'creation',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['green'],
    // },
    orangebandanaset: {
        type: 'Bag',
        color: 'Orange Bandana Set',
        img: 'OrangeBandanaSet.jpg',
        param: 'orangebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['orange'],
    },
    yellowbandanaset: {
        type: 'Bag',
        color: 'Yellow Bandana Set',
        img: 'YellowBandanaSet.jpg',
        param: 'yellowbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['yellow'],
    },
    // greenbandanaset: {
    //     type: 'Bag',
    //     color: 'Green Bandana',
    //     img: 'GreenBandana.jpg',
    //     param: 'greenbandana',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['green'],
    // },
    // limebandanaset: {
    //     type: 'Bag',
    //     color: 'Lime Bandana',
    //     img: 'LimeBandana.jpg',
    //     param: 'limebandana',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['green'],
    // },
    // skybandanaset: {
    //     type: 'Bag',
    //     color: 'Sky Bandana',
    //     img: 'SkyBandana.jpg',
    //     param: 'skybandana',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['blue'],
    // },
    brownbandanaset: {
        type: 'Bag',
        color: 'Brown Bandana Set',
        img: 'BrownBandanaSet.jpg',
        param: 'brownbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown'],
    },
    beigebandanaset: {
        type: 'Bag',
        color: 'Beige Bandana Set',
        img: 'BeigeBandanaSet.jpg',
        param: 'beigebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown', 'beige'],
    },
    // hibiscusbandanaset: {
    //     type: 'Bag',
    //     color: 'Hibiscus Bandana',
    //     img: 'HibiscusBandana.jpg',
    //     param: 'hibiscusbandana',
    //     price: setPrice,
    //     category: 'bandana',
    //     angled: true,
    //     tags: ['brown', 'hibiscus'],
    // },
    bluebandanaset: {
        type: 'Bag',
        color: 'Blue Bandana Set',
        img: 'BlueBandanaSet.jpg',
        param: 'bluebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['navy'],
    },
    // ///////////////
    // // PATTERNED //
    // //////////////
    hollywoodset: {
        type: 'Bag',
        color: 'Hollywood Set',
        img: 'HollywoodSet.jpg',
        param: 'hollywoodset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    armycamoset: {
        type: 'Bag',
        color: 'Army Camo Set',
        img: 'ArmyCamoSet.jpg',
        param: 'armycamoset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    navycamoset: {
        type: 'Bag',
        color: 'Navy Camo Set',
        img: 'NavyCamoSet.jpg',
        param: 'navycamoset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    camouflageset: {
        type: 'Bag',
        color: 'Camouflage Set',
        img: 'CamouflageSet.jpg',
        param: 'camouflageset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    graceset: {
        type: 'Bag',
        color: 'Grace Set',
        img: 'GraceSet.jpg',
        param: 'graceset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'yellow'],
    },
    // hopeset: {
    //     type: 'Bag',
    //     color: 'Hope',
    //     img: 'Hope.jpg',
    //     param: 'hope',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['blue', 'purple'],
    // },
    redpolkadotset: {
        type: 'Bag',
        color: 'Red Polkadot Set',
        img: 'RedPolkadotSet.jpg',
        param: 'redpolkadotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    greypolkadotset: {
        type: 'Bag',
        color: 'Grey Polkadot Set',
        img: 'GreyPolkadotSet.jpg',
        param: 'greypolkadotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    blotset: {
        type: 'Bag',
        color: 'Blot Set',
        img: 'BlotSet.jpg',
        param: 'blotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    redblotset: {
        type: 'Bag',
        color: 'Red Blot Set',
        img: 'RedBlotSet.jpg',
        param: 'redblotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    superstarset: {
        type: 'Bag',
        color: 'Superstar Set',
        img: 'SuperstarSet.jpg',
        param: 'superstarset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'colorful'],
    },
    nightskyset: {
        type: 'Bag',
        color: 'Night Sky Set',
        img: 'NightSkySet.jpg',
        param: 'nightskyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    lockeset: {
        type: 'Bag',
        color: 'Locke Set',
        img: 'LockeSet.jpg',
        param: 'lockeset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    esteemedset: {
        type: 'Bag',
        color: 'Esteemed Set',
        img: 'EsteemedSet.jpg',
        param: 'esteemedset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    polkset: {
        type: 'Bag',
        color: 'Polk Set',
        img: 'PolkSet.jpg',
        param: 'polkset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    // starsset: {
    //     type: 'Bag',
    //     color: 'Stars',
    //     img: 'Stars.jpg',
    //     param: 'stars',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black'],
    // },
    dreamcatcherset: {
        type: 'Bag',
        color: 'Dreamcatcher Set',
        img: 'DreamcatcherSet.jpg',
        param: 'dreamcatcherset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'red'],
    },
    snowflakeset: {
        type: 'Bag',
        color: 'Snowflake Set',
        img: 'SnowflakeSet.jpg',
        param: 'snowflakeset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: ['blue'],
    },
    comicset: {
        type: 'Bag',
        color: 'Comic Set',
        img: 'ComicSet.jpg',
        param: 'comicset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['white'],
    },
    vivaset: {
        type: 'Bag',
        color: 'Viva Set',
        img: 'VivaSet.jpg',
        param: 'vivaset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    christmasspiritset: {
        type: 'Bag',
        color: 'Christmas Spirit Set',
        img: 'ChristmasSpiritSet.jpg',
        param: 'christmasspiritset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: ['green'],
    },
    ayanset: {
        type: 'Bag',
        color: 'AyanSet',
        img: 'AyanSet.jpg',
        param: 'ayanset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    alloyset: {
        type: 'Bag',
        color: 'Alloy Set',
        img: 'AlloySet.jpg',
        param: 'alloyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['grey'],
    },
    // calaveraset: {
    //     type: 'Bag',
    //     color: 'Calavera',
    //     img: 'Calavera.jpg',
    //     param: 'calavera',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['red'],
    // },
    // moonlightset: {
    //     type: 'Bag',
    //     color: 'Moonlight',
    //     img: 'Moonlight.jpg',
    //     param: 'moonlight',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['red'],
    // },
    zigzagset: {
        type: 'Bag',
        color: 'Zig Zag Set',
        img: 'ZigZagSet.jpg',
        param: 'zigzagset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    // checkersset: {
    //     type: 'Bag',
    //     color: 'Checkers',
    //     img: 'Checkers.jpg',
    //     param: 'checkers',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // mortesset: {
    //     type: 'Bag',
    //     color: 'Mortes',
    //     img: 'Mortes.jpg',
    //     param: 'mortes',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // commandmentsset: {
    //     type: 'Bag',
    //     color: 'Commandments',
    //     img: 'Commandments.jpg',
    //     param: 'commandments',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['red', 'yellow', 'gold'],
    // },
    // rhombusset: {
    //     type: 'Bag',
    //     color: 'Rhombus',
    //     img: 'Rhombus.jpg',
    //     param: 'rhombus',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // minnieset: {
    //     type: 'Bag',
    //     color: 'Minnie',
    //     img: 'Minnie.jpg',
    //     param: 'minnie',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['red'],
    // },
    reddottedset: {
        type: 'Bag',
        color: 'Red Dotted Set',
        img: 'RedDottedSet.jpg',
        param: 'reddottedset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'white'],
    },
    // paisleyset: {
    //     type: 'Bag',
    //     color: 'Paisley',
    //     img: 'Paisley.jpg',
    //     param: 'paisley',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // artifactset: {
    //     type: 'Bag',
    //     color: 'Artifact',
    //     img: 'Artifact.jpg',
    //     param: 'artifact',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black'],
    // },
    // artisanblackset: {
    //     type: 'Bag',
    //     color: 'Artisan Black',
    //     img: 'ArtisanBlack.jpg',
    //     param: 'artisanblack',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: [],
    // },
    kotaset: {
        type: 'Bag',
        color: 'Kota Set',
        img: 'KotaSet.jpg',
        param: 'kotaset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    azuriteset: {
        type: 'Bag',
        color: 'Azurite Set',
        img: 'AzuriteSet.jpg',
        param: 'azuriteset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    marbleset: {
        type: 'Bag',
        color: 'Marble Set',
        img: 'MarbleSet.jpg',
        param: 'marbleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['grey'],
    },
    // eveningset: {
    //     type: 'Bag',
    //     color: 'Evening',
    //     img: 'Evening.jpg',
    //     param: 'evening',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['orange', 'brown'],
    // },
    butterflyset: {
        type: 'Bag',
        color: 'Butterfly Set',
        img: 'ButterflySet.jpg',
        param: 'butterflyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'purple'],
    },
    // heartsset: {
    //     type: 'Bag',
    //     color: 'Hearts',
    //     img: 'Hearts.jpg',
    //     param: 'hearts',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'red'],
    // },
    dazzleset: {
        type: 'Bag',
        color: 'Dazzle Set',
        img: 'DazzleSet.jpg',
        param: 'dazzleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    // heiroset: {
    //     type: 'Bag',
    //     color: 'Heiro',
    //     img: 'Heiro.jpg',
    //     param: 'heiro',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown'],
    // },
    splashset: {
        type: 'Bag',
        color: 'Splash Set',
        img: 'SplashSet.jpg',
        param: 'splashset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    cherriesset: {
        type: 'Bag',
        color: 'Cherries Set',
        img: 'CherriesSet.jpg',
        param: 'cherriesset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    uniqueset: {
        type: 'Bag',
        color: 'Unique Set',
        img: 'UniqueSet.jpg',
        param: 'uniqueset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'yellow'],
    },
    // canvasset: {
    //     type: 'Bag',
    //     color: 'Canvas',
    //     img: 'Canvas.jpg',
    //     param: 'canvas',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['red'],
    // },
    // starpowerset: {
    //     type: 'Bag',
    //     color: 'Starpower',
    //     img: 'Starpower.jpg',
    //     param: 'starpower',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['purple', 'pink', 'blue'],
    // },
    // swirlset: {
    //     type: 'Bag',
    //     color: 'Swirl',
    //     img: 'Swirl.jpg',
    //     param: 'swirl',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['purple'],
    // },
    // deepset: {
    //     type: 'Bag',
    //     color: 'Deep',
    //     img: 'Deep.jpg',
    //     param: 'deep',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['purple'],
    // },
    // illusionset: {
    //     type: 'Bag',
    //     color: 'Illusion',
    //     img: 'Illusion.jpg',
    //     param: 'illusion',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: [],
    // },
    ascendset: {
        type: 'Bag',
        color: 'Ascend Set',
        img: 'AscendSet.jpg',
        param: 'ascendset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['white', 'blue'],
    },
    // bubblegumset: {
    //     type: 'Bag',
    //     color: 'Bubblegum',
    //     img: 'Bubblegum.jpg',
    //     param: 'bubblegum',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['colorful'],
    // },
    starspangledset: {
        type: 'Bag',
        color: 'Star Spangled Set',
        img: 'StarSpangledSet.jpg',
        param: 'starspangledset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'blue'],
    },
    // artisticset: {
    //     type: 'Bag',
    //     color: 'Artistic',
    //     img: 'Artistic.jpg',
    //     param: 'artistic',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['colorful'],
    // },
    // universeset: {
    //     type: 'Bag',
    //     color: 'Universe',
    //     img: 'Universe.jpg',
    //     param: 'universe',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['pink'],
    // },
    // galaxyset: {
    //     type: 'Bag',
    //     color: 'Galaxy',
    //     img: 'Galaxy.jpg',
    //     param: 'galaxy',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['colorful', 'black'],
    // },
    // twineset: {
    //     type: 'Bag',
    //     color: 'Twine',
    //     img: 'Twine.jpg',
    //     param: 'twine',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['pink', 'red'],
    // },
    // signatureset: {
    //     type: 'Bag',
    //     color: 'Signature',
    //     img: 'Signature.jpg',
    //     param: 'signature',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown', 'yellow'],
    // },
    grandset: {
        type: 'Bag',
        color: 'Grand Set',
        img: 'GrandSet.jpg',
        param: 'grandset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    hearthset: {
        type: 'Bag',
        color: 'Hearth Set',
        img: 'HearthSet.jpg',
        param: 'hearthset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    // sparkleset: {
    //     type: 'Bag',
    //     color: 'Sparkle',
    //     img: 'Sparkle.jpg',
    //     param: 'sparkle',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black'],
    // },
    // magneticset: {
    //     type: 'Bag',
    //     color: 'Magnetic',
    //     img: 'Magnetic.jpg',
    //     param: 'magnetic',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['blue', 'yellow', 'teal'],
    // },
    // radiantset: {
    //     type: 'Bag',
    //     color: 'Radiant',
    //     img: 'Radiant.jpg',
    //     param: 'radiant',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['yellow', 'orange', 'red'],
    // },
    eraset: {
        type: 'Bag',
        color: 'Era Set',
        img: 'EraSet.jpg',
        param: 'eraset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    // flamesset: {
    //     type: 'Bag',
    //     color: 'Flames',
    //     img: 'Flames.jpg',
    //     param: 'flames',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['yellow', 'orange', 'red'],
    // },
    // nurseset: {
    //     type: 'Bag',
    //     color: 'Nurse',
    //     img: 'Nurse.jpg',
    //     param: 'nurse',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['pink', 'red'],
    // },
    appleset: {
        type: 'Bag',
        color: 'Apple Set',
        img: 'AppleSet.jpg',
        param: 'appleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    fancyset: {
        type: 'Bag',
        color: 'Fancy Set',
        img: 'FancySet.jpg',
        param: 'fancyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'pink'],
    },
    heelsset: {
        type: 'Bag',
        color: 'Heels Set',
        img: 'HeelsSet.jpg',
        param: 'heelsset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    // ladybugset: {
    //     type: 'Bag',
    //     color: 'Ladybug',
    //     img: 'Ladybug.jpg',
    //     param: 'ladybug',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['red'],
    // },
    forestset: {
        type: 'Bag',
        color: 'Forest Set',
        img: 'ForestSet.jpg',
        param: 'forestset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    wildlifeset: {
        type: 'Bag',
        color: 'Wildlife Set',
        img: 'WildlifeSet.jpg',
        param: 'wildlifeset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    blackdottedset: {
        type: 'Bag',
        color: 'Black Dotted Set',
        img: 'BlackDottedSet.jpg',
        param: 'blackdottedset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    spotsset: {
        type: 'Bag',
        color: 'Spots Set',
        img: 'SpotsSet.jpg',
        param: 'spotsset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white', 'dots'],
    },
    gardenerset: {
        type: 'Bag',
        color: 'GardenerSet',
        img: 'GardenerSet.jpg',
        param: 'gardenerset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    // polkset: {
    //     type: 'Bag',
    //     color: 'Polk',
    //     img: 'Polk.jpg',
    //     param: 'polk',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // polkadotsset: {
    //     type: 'Bag',
    //     color: 'Polkadots',
    //     img: 'Polkadots.jpg',
    //     param: 'polkadots',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['yellow'],
    // },
    // galaset: {
    //     type: 'Bag',
    //     color: 'Gala',
    //     img: 'Gala.jpg',
    //     param: 'gala',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'green', 'grey'],
    // },
    // soccerset: {
    //     type: 'Bag',
    //     color: 'Soccer',
    //     img: 'Soccer.jpg',
    //     param: 'soccer',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: [],
    // },
    // carveset: {
    //     type: 'Bag',
    //     color: 'Carve',
    //     img: 'Carve.jpg',
    //     param: 'carve',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // walnutset: {
    //     type: 'Bag',
    //     color: 'Walnut',
    //     img: 'Walnut.jpg',
    //     param: 'walnut',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // rainbowset: {
    //     type: 'Bag',
    //     color: 'Rainbow',
    //     img: 'Rainbow.jpg',
    //     param: 'rainbow',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['colorful'],
    // },
    // stripeset: {
    //     type: 'Bag',
    //     color: 'Stripe',
    //     img: 'Stripe.jpg',
    //     param: 'stripe',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['colorful'],
    // },
    // plaidset: {
    //     type: 'Bag',
    //     color: 'Plaid',
    //     img: 'Plaid.jpg',
    //     param: 'plaid',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // tribalset: {
    //     type: 'Bag',
    //     color: 'Tribal',
    //     img: 'Tribal.jpg',
    //     param: 'tribal',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // redplaidset: {
    //     type: 'Bag',
    //     color: 'Red Plaid',
    //     img: 'RedPlaid.jpg',
    //     param: 'redplaid',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'red'],
    // },
    // enamorset: {
    //     type: 'Bag',
    //     color: 'Enamor',
    //     img: 'Enamor.jpg',
    //     param: 'enamor',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // menaceset: {
    //     type: 'Bag',
    //     color: 'Menace',
    //     img: 'Menace.jpg',
    //     param: 'menace',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['green'],
    // },
    // artisanredset: {
    //     type: 'Bag',
    //     color: 'Artisan Red',
    //     img: 'ArtisanRed.jpg',
    //     param: 'artisanred',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: false,
    //     tags: ['pink'],
    // },
    musicset: {
        type: 'Bag',
        color: 'Music',
        img: 'Music.jpg',
        param: 'music',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    musicalset: {
        type: 'Bag',
        color: 'Musical Set',
        img: 'MusicalSet.jpg',
        param: 'musicalset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    // pianistset: {
    //     type: 'Bag',
    //     color: 'Pianist',
    //     img: 'Pianist.jpg',
    //     param: 'pianist',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // trumpetset: {
    //     type: 'Bag',
    //     color: 'Trumpet',
    //     img: 'Trumpet.jpg',
    //     param: 'trumpet',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     XLUnavailable: true,
    //     tags: ['orange'],
    // },
    // clarinetset: {
    //     type: 'Bag',
    //     color: 'Clarinet',
    //     img: 'Clarinet.jpg',
    //     param: 'clarinet',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    pinkcamoset: {
        type: 'Bag',
        color: 'Pink Camo Set',
        img: 'PinkCamoSet.jpg',
        param: 'pinkcamoset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    firefighterset: {
        type: 'Bag',
        color: 'Firefighter Set',
        img: 'FirefighterSet.jpg',
        param: 'firefighterset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    // allureset: {
    //     type: 'Bag',
    //     color: 'Allure',
    //     img: 'Allure.jpg',
    //     param: 'allure',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['purple', 'violet', 'lavender'],
    // },
    // motionset: {
    //     type: 'Bag',
    //     color: 'Motion',
    //     img: 'Motion.jpg',
    //     param: 'motion',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['green'],
    // },
    // nativeset: {
    //     type: 'Bag',
    //     color: 'Native',
    //     img: 'Native.jpg',
    //     param: 'native',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['orange', 'brown'],
    // },
    // lavandeset: {
    //     type: 'Bag',
    //     color: 'La Vandé',
    //     img: 'Lavande.jpg',
    //     param: 'lavande',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'pink'],
    // },
    // indusset: {
    //     type: 'Bag',
    //     color: 'Indus',
    //     img: 'Indus.jpg',
    //     param: 'indus',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'orange', 'teal'],
    // },
    // rezaset: {
    //     type: 'Bag',
    //     color: 'Reza',
    //     img: 'Reza.jpg',
    //     param: 'reza',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['green'],
    // },
    ancientset: {
        type: 'Bag',
        color: 'Ancient Set',
        img: 'AncientSet.jpg',
        param: 'ancientset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    // arrowset: {
    //     type: 'Bag',
    //     color: 'Arrow',
    //     img: 'Arrow.jpg',
    //     param: 'arrow',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: [],
    // },
    shadesset: {
        type: 'Bag',
        color: 'Shades Set',
        img: 'ShadesSet.jpg',
        param: 'shadesset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    spinset: {
        type: 'Bag',
        color: 'Spin Set',
        img: 'SpinSet.jpg',
        param: 'spinset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    // nightset: {
    //     type: 'Bag',
    //     color: 'Night',
    //     img: 'Night.jpg',
    //     param: 'night',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['blue'],
    // },
    woodsset: {
        type: 'Bag',
        color: 'Woods Set',
        img: 'WoodsSet.jpg',
        param: 'woodsset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'black', 'brown'],
    },
    // winterset: {
    //     type: 'Bag',
    //     color: 'Winter',
    //     img: 'Winter.jpg',
    //     param: 'winter',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'blue', 'white'],
    // },
    // decorset: {
    //     type: 'Bag',
    //     color: 'Decor',
    //     img: 'Decor.jpg',
    //     param: 'decor',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['teal', 'orange', 'brown'],
    // },
    // geoset: {
    //     type: 'Bag',
    //     color: 'Geo',
    //     img: 'Geo.jpg',
    //     param: 'geo',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['teal', 'orange', 'brown'],
    // },
    // chevronsset: {
    //     type: 'Bag',
    //     color: 'Chevrons',
    //     img: 'Chevrons.jpg',
    //     param: 'chevrons',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // ////////////
    // // ANIMAL //
    // ///////////
    // joyset: {
    //     type: 'Bag',
    //     color: 'Joy',
    //     img: 'Joy.jpg',
    //     param: 'joy',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['black', 'dog'],
    // },
    pawsset: {
        type: 'Bag',
        color: 'Paws Set',
        img: 'PawsSet.jpg',
        param: 'pawsset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    lovableset: {
        type: 'Bag',
        color: 'Lovable Set',
        img: 'LovableSet.jpg',
        param: 'lovableset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    pupperset: {
        type: 'Bag',
        color: 'Pupper Set',
        img: 'PupperSet.jpg',
        param: 'pupperset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    rainbowpawset: {
        type: 'Bag',
        color: 'Rainbow Paw Set',
        img: 'RainbowPawSet.jpg',
        param: 'rainbowpawset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    cobraskinset: {
        type: 'Bag',
        color: 'Cobraskin Set',
        img: 'CobraskinSet.jpg',
        param: 'cobraskinset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    jaguarset: {
        type: 'Bag',
        color: 'Jaguar Set',
        img: 'JaguarSet.jpg',
        param: 'jaguarset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    felineset: {
        type: 'Bag',
        color: 'Feline Set',
        img: 'FelineSet.jpg',
        param: 'felineset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['orange'],
    },
    milkset: {
        type: 'Bag',
        color: 'Milk Set',
        img: 'MilkSet.jpg',
        param: 'milkset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    // doggieset: {
    //     type: 'Bag',
    //     color: 'Doggie',
    //     img: 'Doggie.jpg',
    //     param: 'doggie',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dog'],
    // },
    sweetieset: {
        type: 'Bag',
        color: 'Sweetie Set',
        img: 'SweetieSet.jpg',
        param: 'sweetieset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    tigerset: {
        type: 'Bag',
        color: 'Tiger Set',
        img: 'TigerSet.jpg',
        param: 'tigerset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['orange'],
    },
    cheetahset: {
        type: 'Bag',
        color: 'Cheetah Set',
        img: 'CheetahSet.jpg',
        param: 'cheetahset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'brown', 'orange'],
    },
    snowleopardset: {
        type: 'Bag',
        color: 'Snow Leopard Set',
        img: 'SnowLeopardSet.jpg',
        param: 'snowleopardset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    himaset: {
        type: 'Bag',
        color: 'Hima Set',
        img: 'HimaSet.jpg',
        param: 'himaset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'blue'],
    },
    elephantset: {
        type: 'Bag',
        color: 'Elephant Set',
        img: 'ElephantSet.jpg',
        param: 'elephantset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    // spiritset: {
    //     type: 'Bag',
    //     color: 'Spirit Set',
    //     img: 'SpiritSet.jpg',
    //     param: 'spiritset',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['black', 'blue', 'red'],
    // },
    // zebraset: {
    //     type: 'Bag',
    //     color: 'Zebra',
    //     img: 'Zebra.jpg',
    //     param: 'zebra',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // dalmationset: {
    //     type: 'Bag',
    //     color: 'Dalmation',
    //     img: 'Dalmation.jpg',
    //     param: 'dalmation',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['white', 'black'],
    // },
    // maldationset: {
    //     type: 'Bag',
    //     color: 'Maldation',
    //     img: 'Maldation.jpg',
    //     param: 'maldation',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['white', 'black'],
    // },
    // skipperset: {
    //     type: 'Bag',
    //     color: 'Skipper',
    //     img: 'Skipper.jpg',
    //     param: 'skipper',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['red'],
    // },
    // rawpset: {
    //     type: 'Bag',
    //     color: 'Rawp',
    //     img: 'Rawp.jpg',
    //     param: 'rawp',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dogs'],
    // },
    // happyset: {
    //     type: 'Bag',
    //     color: 'Happy',
    //     img: 'Happy.jpg',
    //     param: 'happy',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: [],
    // },
    // bunniesset: {
    //     type: 'Bag',
    //     color: 'Bunnies',
    //     img: 'Bunnies.jpg',
    //     param: 'bunnies',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['white'],
    // },
    // woofset: {
    //     type: 'Bag',
    //     color: 'Woof',
    //     img: 'Woof.jpg',
    //     param: 'woof',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dog', 'red'],
    // },
    arfset: {
        type: 'Bag',
        color: 'Arf Set',
        img: 'ArfSet.jpg',
        param: 'arfset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'blue'],
    },
    // underwaterset: {
    //     type: 'Bag',
    //     color: 'Underwater',
    //     img: 'Underwater.jpg',
    //     param: 'underwater',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // mermaidset: {
    //     type: 'Bag',
    //     color: 'Mermaid',
    //     img: 'Mermaid.jpg',
    //     param: 'mermaid',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // whaleset: {
    //     type: 'Bag',
    //     color: 'Whale',
    //     img: 'Whale.jpg',
    //     param: 'whale',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    jungleset: {
        type: 'Bag',
        color: 'Jungle Set',
        img: 'JungleSet.jpg',
        param: 'jungleset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    toadset: {
        type: 'Bag',
        color: 'Toad Set',
        img: 'ToadSet.jpg',
        param: 'toadset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    goldenunicornset: {
        type: 'Bag',
        color: 'Golden Unicorn Set',
        img: 'GoldenUnicornSet.jpg',
        param: 'goldenunicornset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    unicornset: {
        type: 'Bag',
        color: 'Unicorn Set',
        img: 'UnicornSet.jpg',
        param: 'unicornset',
        price: setPrice,
        category: 'animal',
        angled: false,
        tags: ['pink'],
    },
    unicornpowerset: {
        type: 'Bag',
        color: 'Unicorn Power Set',
        img: 'UnicornPowerSet.jpg',
        param: 'unicornpowerset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    // elephantset: {
    //     type: 'Bag',
    //     color: 'Elephant',
    //     img: 'Elephant.jpg',
    //     param: 'elephant',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['pink'],
    // },
    bearburyset: {
        type: 'Bag',
        color: 'Bearbury Set',
        img: 'BearburySet.jpg',
        param: 'bearburyset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    // adorableset: {
    //     type: 'Bag',
    //     color: 'Adorable',
    //     img: 'Adorable.jpg',
    //     param: 'adorable',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['cats'],
    // },
    // kittensset: {
    //     type: 'Bag',
    //     color: 'Kittens',
    //     img: 'Kittens.jpg',
    //     param: 'kittens',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['cat', 'brown'],
    // },
    // dawgset: {
    //     type: 'Bag',
    //     color: 'Dawg',
    //     img: 'Dawg.jpg',
    //     param: 'dawg',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dog', 'brown'],
    // },
    // coolioset: {
    //     type: 'Bag',
    //     color: 'Coolio',
    //     img: 'Coolio.jpg',
    //     param: 'coolio',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dog'],
    // },
    // purrset: {
    //     type: 'Bag',
    //     color: 'Purr',
    //     img: 'Purr.jpg',
    //     param: 'purr',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['red', 'cats'],
    // },
    // meowset: {
    //     type: 'Bag',
    //     color: 'Meow',
    //     img: 'Meow.jpg',
    //     param: 'meow',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['pink', 'cats'],
    // },
    // cuteset: {
    //     type: 'Bag',
    //     color: 'Cute',
    //     img: 'Cute.jpg',
    //     param: 'cute',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'cat', 'navy'],
    // },
    // xrayset: {
    //     type: 'Bag',
    //     color: 'X-Ray',
    //     img: 'X-Ray.jpg',
    //     param: 'xray',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'cat', 'navy'],
    // },
    // milkset: {
    //     type: 'Bag',
    //     color: 'Milk',
    //     img: 'Milk.jpg',
    //     param: 'milk',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['white', 'black'],
    // },
    mooset: {
        type: 'Bag',
        color: 'Moo Set',
        img: 'MooSet.jpg',
        param: 'mooset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey', 'black'],
    },
    // jaguarset: {
    //     type: 'Bag',
    //     color: 'Jaguar',
    //     img: 'Jaguar.jpg',
    //     param: 'jaguar',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // rooset: {
    //     type: 'Bag',
    //     color: 'Roo',
    //     img: 'Roo.jpg',
    //     param: 'roo',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // hunterset: {
    //     type: 'Bag',
    //     color: 'Hunter',
    //     img: 'Hunter.jpg',
    //     param: 'hunter',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // featherset: {
    //     type: 'Bag',
    //     color: 'Feather',
    //     img: 'Feather.jpg',
    //     param: 'feather',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['white', 'grey'],
    // },
    // flamingoset: {
    //     type: 'Bag',
    //     color: 'Flamingo',
    //     img: 'Flamingo.jpg',
    //     param: 'flamingo',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'orange'],
    // },
    // blackandwhiteset: {
    //     type: 'Bag',
    //     color: 'Black & White',
    //     img: 'Black&White.jpg',
    //     param: 'blackandwhite',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['black', 'white'],
    // },
    // pandaset: {
    //     type: 'Bag',
    //     color: 'Panda',
    //     img: 'Panda.jpg',
    //     param: 'panda',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['grey'],
    // },
    // ranchset: {
    //     type: 'Bag',
    //     color: 'Ranch',
    //     img: 'Ranch.jpg',
    //     param: 'ranch',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,

    //     tags: ['grey'],
    // },
    // violetredzebraset: {
    //     type: 'Bag',
    //     color: 'Violet Red Zebra',
    //     img: 'VioletRedZebra.jpg',
    //     param: 'violetredzebra',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['purple', 'magenta'],
    // },
    // cobraset: {
    //     type: 'Bag',
    //     color: 'Cobra',
    //     img: 'Cobra.jpg',
    //     param: 'cobra',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['animal', 'orange', 'brown'],
    // },
    // snakeskinset: {
    //     type: 'Bag',
    //     color: 'Snakeskin',
    //     img: 'Snakeskin.jpg',
    //     param: 'snakeskin',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['animal', 'orange', 'brown'],
    // },
    // playset: {
    //     type: 'Bag',
    //     color: 'Play',
    //     img: 'Play.jpg',
    //     param: 'play',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'red'],
    // },
    // eagleset: {
    //     type: 'Bag',
    //     color: 'Eagle',
    //     img: 'Eagle.jpg',
    //     param: 'eagle',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue', 'bird'],
    // },
    // owlsset: {
    //     type: 'Bag',
    //     color: 'Owls',
    //     img: 'Owls.jpg',
    //     param: 'owls',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['brown'],
    // },
    // owliesset: {
    //     type: 'Bag',
    //     color: 'Owlies',
    //     img: 'Owlies.jpg',
    //     param: 'owlies',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['grey'],
    // },
    owlettesset: {
        type: 'Bag',
        color: 'Owlettesset',
        img: 'OwlettesSet.jpg',
        param: 'owlettesset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey'],
    },
    madagascarset: {
        type: 'Bag',
        color: 'Madagascar Set',
        img: 'MadagascarSet.jpg',
        param: 'madagascarset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    scoutset: {
        type: 'Bag',
        color: 'Scout Set',
        img: 'ScoutSet.jpg',
        param: 'scoutset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    // parrotsset: {
    //     type: 'Bag',
    //     color: 'Parrots',
    //     img: 'Parrots.jpg',
    //     param: 'parrots',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['bird', 'colorful'],
    // },
    // toucanset: {
    //     type: 'Bag',
    //     color: 'Toucan',
    //     img: 'Toucan.jpg',
    //     param: 'toucan',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['bird', 'black'],
    // },
    // furrballsset: {
    //     type: 'Bag',
    //     color: 'Furrballs',
    //     img: 'Furrballs.jpg',
    //     param: 'furrballs',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['cats'],
    // },
    poochset: {
        type: 'Bag',
        color: 'Pooch Set',
        img: 'PoochSet.jpg',
        param: 'poochset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs'],
    },
    // kennelset: {
    //     type: 'Bag',
    //     color: 'Kennel',
    //     img: 'Kennel.jpg',
    //     param: 'kennel',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dogs', 'brown'],
    // },
    // barkinglotset: {
    //     type: 'Bag',
    //     color: 'Barking Lot',
    //     img: 'BarkingLot.jpg',
    //     param: 'barkinglot',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['dogs', 'brown'],
    // },
    // llamaset: {
    //     type: 'Bag',
    //     color: 'Llama',
    //     img: 'Llama.jpg',
    //     param: 'llama',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // arcticset: {
    //     type: 'Bag',
    //     color: 'Arctic',
    //     img: 'Arctic.jpg',
    //     param: 'arctic',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // seahorseset: {
    //     type: 'Bag',
    //     color: 'Seahorse',
    //     img: 'Seahorse.jpg',
    //     param: 'seahorse',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // penguinsset: {
    //     type: 'Bag',
    //     color: 'Penguins',
    //     img: 'Penguins.jpg',
    //     param: 'penguins',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['white', 'grey', 'blue'],
    // },
    // dreamyset: {
    //     type: 'Bag',
    //     color: 'Dreamy',
    //     img: 'Dreamy.jpg',
    //     param: 'dreamy',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: ['blue'],
    // },
    dinoset: {
        type: 'Bag',
        color: 'Dino Set',
        img: 'DinoSet.jpg',
        param: 'dinoset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    // //////////////
    // // HAWAIIAN //
    // //////////////
    hulaset: {
        type: 'Bag',
        color: 'Hula Set',
        img: 'HulaSet.jpg',
        param: 'hulaset',
        price: setPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['pink', 'red', 'green'],
    },
    // pondset: {
    //     type: 'Bag',
    //     color: 'Pond',
    //     img: 'Pond.jpg',
    //     param: 'pond',
    //     price: setPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['blue'],
    // },
    suaveset: {
        type: 'Bag',
        color: 'Suave Set',
        img: 'SuaveSet.jpg',
        param: 'suaveset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['grey'],
    },
    luauset: {
        type: 'Bag',
        color: 'Luau Set',
        img: 'LuauSet.jpg',
        param: 'luauset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    palmsset: {
        type: 'Bag',
        color: 'Palms Set',
        img: 'PalmsSet.jpg',
        param: 'palmsset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['black'],
    },
    // koiset: {
    //     type: 'Bag',
    //     color: 'Koi',
    //     img: 'Koi.jpg',
    //     param: 'koi',
    //     price: setPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['red', 'pink'],
    // },
    sunsetset: {
        type: 'Bag',
        color: 'Sunset Set',
        img: 'SunsetSet.jpg',
        param: 'sunsetset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    buttercupset: {
        type: 'Bag',
        color: 'Buttercup Set',
        img: 'ButtercupSet.jpg',
        param: 'buttercupset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    // skyset: {
    //     type: 'Bag',
    //     color: 'Sky',
    //     img: 'Sky.jpg',
    //     param: 'sky',
    //     price: setPrice,
    //     category: 'hawaiian',
    //     angled: false,
    //     tags: ['blue'],
    // },
    // alohaset: {
    //     type: 'Bag',
    //     color: 'Aloha',
    //     img: 'Aloha.jpg',
    //     param: 'aloha',
    //     price: setPrice,
    //     category: 'hawaiian',
    //     angled: true,
    //     tags: ['red', 'orange', 'yellow'],
    // },
    glowset: {
        type: 'Bag',
        color: 'Glow Set',
        img: 'GlowSet.jpg',
        param: 'glowset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    canopyset: {
        type: 'Bag',
        color: 'Canopy Set',
        img: 'CanopySet.jpg',
        param: 'canopyset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['pink', 'green'],
    },
    // duskset: {
    //     type: 'Bag',
    //     color: 'Dusk',
    //     img: 'Dusk.jpg',
    //     param: 'dusk',
    //     price: setPrice,
    //     category: 'hawaiian',
    //     angled: false,
    //     tags: ['pink'],
    // },
    // surfset: {
    //     type: 'Bag',
    //     color: 'Surf',
    //     img: 'Surf.jpg',
    //     param: 'surf',
    //     price: setPrice,
    //     category: 'hawaiian',
    //     angled: false,
    //     tags: ['grey', 'yellow'],
    // },
    honoluluset: {
        type: 'Bag',
        color: 'Honolulu Set',
        img: 'HonoluluSet.jpg',
        param: 'honoluluset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red'],
    },
    // ////////////
    // // FLORAL //
    // ////////////,
    // elegantset: {
    //     type: 'Bag',
    //     color: 'Elegant',
    //     img: 'Elegant.jpg',
    //     param: 'elegant',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'gold', 'yellow'],
    // },
    eleganceset: {
        type: 'Bag',
        color: 'Elegance Set',
        img: 'EleganceSet.jpg',
        param: 'eleganceset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['grey', 'gold', 'yellow'],
    },
    orientset: {
        type: 'Bag',
        color: 'Orient Set',
        img: 'OrientSet.jpg',
        param: 'orientset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red', 'gold', 'yellow'],
    },
    gracefulset: {
        type: 'Bag',
        color: 'Graceful Set',
        img: 'GracefulSet.jpg',
        param: 'gracefulset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    divineset: {
        type: 'Bag',
        color: 'Divine Set',
        img: 'DivineSet.jpg',
        param: 'divineset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    fragrantset: {
        type: 'Bag',
        color: 'Fragrant Set',
        img: 'FragrantSet.jpg',
        param: 'fragrantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    brilliantset: {
        type: 'Bag',
        color: 'Brilliant Set',
        img: 'BrilliantSet.jpg',
        param: 'brilliantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'blue'],
    },
    // charmset: {
    //     type: 'Bag',
    //     color: 'Charm',
    //     img: 'Charm.jpg',
    //     param: 'charm',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink'],
    // },
    vibrantset: {
        type: 'Bag',
        color: 'Vibrant Set',
        img: 'VibrantSet.jpg',
        param: 'vibrantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'blue'],
    },
    // sereneset: {
    //     type: 'Bag',
    //     color: 'Serene',
    //     img: 'Serene.jpg',
    //     param: 'serene',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black'],
    // },
    // bouquetset: {
    //     type: 'Bag',
    //     color: 'Bouquet',
    //     img: 'Bouquet.jpg',
    //     param: 'bouquet',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'purple'],
    // },
    // lunaset: {
    //     type: 'Bag',
    //     color: 'Luna',
    //     img: 'Luna.jpg',
    //     param: 'luna',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['white', 'blue'],
    // },
    crystallisset: {
        type: 'Bag',
        color: 'Crystallis Set',
        img: 'CrystallisSet.jpg',
        param: 'crystallisset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'black'],
    },
    ecstaticset: {
        type: 'Bag',
        color: 'Ecstatic Set',
        img: 'EcstaticSet.jpg',
        param: 'ecstaticset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['orange'],
    },
    // amethystset: {
    //     type: 'Bag',
    //     color: 'Amethyst',
    //     img: 'Amethyst.jpg',
    //     param: 'amethyst',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'violet'],
    // },
    // glistenset: {
    //     type: 'Bag',
    //     color: 'Glisten',
    //     img: 'Glisten.jpg',
    //     param: 'glisten',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'violet'],
    // },
    growthset: {
        type: 'Bag',
        color: 'Growth Set',
        img: 'GrowthSet.jpg',
        param: 'growthset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    // maroonaset: {
    //     type: 'Bag',
    //     color: 'Maroona',
    //     img: 'Maroona.jpg',
    //     param: 'maroona',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['maroon', 'red'],
    // },
    curaset: {
        type: 'Bag',
        color: 'Cura Set',
        img: 'CuraSet.jpg',
        param: 'curaset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['maroon', 'red'],
    },
    // wondrousset: {
    //     type: 'Bag',
    //     color: 'Wondrous',
    //     img: 'Wondrous.jpg',
    //     param: 'wondrous',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'gold', 'yellow'],
    // },
    aretiaset: {
        type: 'Bag',
        color: 'Aretia Set',
        img: 'AretiaSet.jpg',
        param: 'aretiaset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'gold'],
    },
    beautyset: {
        type: 'Bag',
        color: 'Beauty Set',
        img: 'BeautySet.jpg',
        param: 'beautyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'yellow'],
    },
    exquisiteset: {
        type: 'Bag',
        color: 'Exquisite Set',
        img: 'ExquisiteSet.jpg',
        param: 'exquisiteset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    // splendidset: {
    //     type: 'Bag',
    //     color: 'Splendid',
    //     img: 'Splendid.jpg',
    //     param: 'splendid',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green'],
    // },
    luckset: {
        type: 'Bag',
        color: 'Luck Set',
        img: 'LuckSet.jpg',
        param: 'luckset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    flowerbedset: {
        type: 'Bag',
        color: 'Flowerbed Set',
        img: 'FlowerbedSet.jpg',
        param: 'flowerbedset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    passionset: {
        type: 'Bag',
        color: 'Passion Set',
        img: 'PassionSet.jpg',
        param: 'passionset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    fluorescentset: {
        type: 'Bag',
        color: 'Fluorescent Set',
        img: 'FluorescentSet.jpg',
        param: 'fluorescentset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black'],
    },
    dahliaset: {
        type: 'Bag',
        color: 'Dahlia Set',
        img: 'DahliaSet.jpg',
        param: 'dahliaset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown'],
    },
    // luxuriousset: {
    //     type: 'Bag',
    //     color: 'Luxurious',
    //     img: 'Luxurious.jpg',
    //     param: 'luxurious',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'violet'],
    // },
    // miracleset: {
    //     type: 'Bag',
    //     color: 'Miracle',
    //     img: 'Miracle.jpg',
    //     param: 'miracle',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'pink'],
    // },
    marvelset: {
        type: 'Bag',
        color: 'Marvel Set',
        img: 'MarvelSet.jpg',
        param: 'marvelset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    // sunlightset: {
    //     type: 'Bag',
    //     color: 'Sunlight',
    //     img: 'Sunlight.jpg',
    //     param: 'sunlight',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['orange'],
    // },
    // delightset: {
    //     type: 'Bag',
    //     color: 'Delight',
    //     img: 'Delight.jpg',
    //     param: 'delight',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['white'],
    // },
    // ornateset: {
    //     type: 'Bag',
    //     color: 'Ornate',
    //     img: 'Ornate.jpg',
    //     param: 'ornate',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue'],
    // },
    swellset: {
        type: 'Bag',
        color: 'Swell Set',
        img: 'SwellSet.jpg',
        param: 'swellset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    // enchantingset: {
    //     type: 'Bag',
    //     color: 'Enchanting',
    //     img: 'Enchanting.jpg',
    //     param: 'enchanting',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue'],
    // },
    flourishset: {
        type: 'Bag',
        color: 'Flourish Set',
        img: 'FlourishSet.jpg',
        param: 'flourishset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    edenset: {
        type: 'Bag',
        color: 'Eden Set',
        img: 'EdenSet.jpg',
        param: 'edenset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    earthset: {
        type: 'Bag',
        color: 'EarthSet',
        img: 'EarthSet.jpg',
        param: 'earthset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown'],
    },
    // majesticset: {
    //     type: 'Bag',
    //     color: 'Majestic',
    //     img: 'Majestic.jpg',
    //     param: 'majestic',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['red', 'yellow'],
    // },
    // lovelyset: {
    //     type: 'Bag',
    //     color: 'Lovely',
    //     img: 'Lovely.jpg',
    //     param: 'lovely',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'red'],
    // },
    pureset: {
        type: 'Bag',
        color: 'Pure Set',
        img: 'PureSet.jpg',
        param: 'pureset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    // clarityset: {
    //     type: 'Bag',
    //     color: 'Clarity',
    //     img: 'Clarity.jpg',
    //     param: 'clarity',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // silvermoonset: {
    //     type: 'Bag',
    //     color: 'Silvermoon',
    //     img: 'Silvermoon.jpg',
    //     param: 'silvermoon',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'silver'],
    // },
    exuberantset: {
        type: 'Bag',
        color: 'Exuberant Set',
        img: 'ExuberantSet.jpg',
        param: 'exuberantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    heavenlyset: {
        type: 'Bag',
        color: 'Heavenly Set',
        img: 'HeavenlySet.jpg',
        param: 'heavenlyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    // affectionset: {
    //     type: 'Bag',
    //     color: 'Affection',
    //     img: 'Affection.jpg',
    //     param: 'affection',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'white'],
    // },
    // sapphireset: {
    //     type: 'Bag',
    //     color: 'Sapphire',
    //     img: 'Sapphire.jpg',
    //     param: 'sapphire',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // rubyset: {
    //     type: 'Bag',
    //     color: 'Ruby',
    //     img: 'Ruby.jpg',
    //     param: 'ruby',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['red'],
    // },
    // preciousset: {
    //     type: 'Bag',
    //     color: 'Precious',
    //     img: 'Precious.jpg',
    //     param: 'precious',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // antiqueset: {
    //     type: 'Bag',
    //     color: 'Antique',
    //     img: 'Antique.jpg',
    //     param: 'antique',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green'],
    // },
    naturalset: {
        type: 'Bag',
        color: 'Natural Set',
        img: 'NaturalSet.jpg',
        param: 'naturalset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow'],
    },
    // honeyset: {
    //     type: 'Bag',
    //     color: 'Honey',
    //     img: 'Honey.jpg',
    //     param: 'honey',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'yellow'],
    // },
    tranquilset: {
        type: 'Bag',
        color: 'Tranquil Set',
        img: 'TranquilSet.jpg',
        param: 'tranquilset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    bloomset: {
        type: 'Bag',
        color: 'Bloom Set',
        img: 'BloomSet.jpg',
        param: 'bloomset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    bubblyset: {
        type: 'Bag',
        color: 'Bubbly Set',
        img: 'BubblySet.jpg',
        param: 'bubblyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    // pleasantriesset: {
    //     type: 'Bag',
    //     color: 'Pleasantries',
    //     img: 'Pleasantries.jpg',
    //     param: 'pleasantries',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'beige', 'brown'],
    // },
    // brightset: {
    //     type: 'Bag',
    //     color: 'Bright',
    //     img: 'Bright.jpg',
    //     param: 'bright',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [''],
    // },
    blossomset: {
        type: 'Bag',
        color: 'Blossom Set',
        img: 'BlossomSet.jpg',
        param: 'blossomset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    bloomingset: {
        type: 'Bag',
        color: 'Blooming Set',
        img: 'BloomingSet.jpg',
        param: 'bloomingset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    // harvestset: {
    //     type: 'Bag',
    //     color: 'Harvest',
    //     img: 'Harvest.jpg',
    //     param: 'harvest',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['brown', 'orange'],
    // },
    // adoreset: {
    //     type: 'Bag',
    //     color: 'Adore',
    //     img: 'Adore.jpg',
    //     param: 'adore',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'pink'],
    // },
    // blissset: {
    //     type: 'Bag',
    //     color: 'Bliss',
    //     img: 'Bliss.jpg',
    //     param: 'bliss',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'purple'],
    // },
    // thriveset: {
    //     type: 'Bag',
    //     color: 'Thrive',
    //     img: 'Thrive.jpg',
    //     param: 'thrive',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'pink'],
    // },
    // flatterset: {
    //     type: 'Bag',
    //     color: 'Flatter',
    //     img: 'Flatter.jpg',
    //     param: 'flatter',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'yellow'],
    // },
    // vividset: {
    //     type: 'Bag',
    //     color: 'Vivid',
    //     img: 'Vivid.jpg',
    //     param: 'vivid',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple'],
    // },
    // zenset: {
    //     type: 'Bag',
    //     color: 'Zen',
    //     img: 'Zen.jpg',
    //     param: 'zen',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    // captivateset: {
    //     type: 'Bag',
    //     color: 'Captivate',
    //     img: 'Captivate.jpg',
    //     param: 'captivate',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'yellow'],
    // },
    // cherishset: {
    //     type: 'Bag',
    //     color: 'Cherish',
    //     img: 'Cherish.jpg',
    //     param: 'cherish',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['brown', 'orange'],
    // },
    rosesset: {
        type: 'Bag',
        color: 'Roses Set',
        img: 'RosesSet.jpg',
        param: 'rosesset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    // prettyset: {
    //     type: 'Bag',
    //     color: 'Pretty',
    //     img: 'Pretty.jpg',
    //     param: 'pretty',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green', 'blue'],
    // },
    // floretset: {
    //     type: 'Bag',
    //     color: 'Floret',
    //     img: 'Floret.jpg',
    //     param: 'floret',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green', 'pink', 'purple'],
    // },
    harmonyset: {
        type: 'Bag',
        color: 'Harmony Set',
        img: 'HarmonySet.jpg',
        param: 'harmonyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    gardenset: {
        type: 'Bag',
        color: 'Garden Set',
        img: 'GardenSet.jpg',
        param: 'gardenset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    // bountifulset: {
    //     type: 'Bag',
    //     color: 'Bountiful',
    //     img: 'Bountiful.jpg',
    //     param: 'bountiful',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['yellow'],
    // },
    // opalset: {
    //     type: 'Bag',
    //     color: 'Opal',
    //     img: 'Opal.jpg',
    //     param: 'opal',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink'],
    // },
    springset: {
        type: 'Bag',
        color: 'Spring Set',
        img: 'SpringSet.jpg',
        param: 'springset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink', 'blue', 'green'],
    },
    // buoyantset: {
    //     type: 'Bag',
    //     color: 'Buoyant',
    //     img: 'Buoyant.jpg',
    //     param: 'buoyant',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['pink'],
    // },
    // cultivateset: {
    //     type: 'Bag',
    //     color: 'Cultivate',
    //     img: 'Cultivate.jpg',
    //     param: 'cultivate',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'orange', 'red'],
    // },
    // treasureset: {
    //     type: 'Bag',
    //     color: 'Treasure',
    //     img: 'Treasure.jpg',
    //     param: 'treasure',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'red'],
    // },
    // perfumeset: {
    //     type: 'Bag',
    //     color: 'Perfume',
    //     img: 'Perfume.jpg',
    //     param: 'perfume',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['purple', 'violet', 'lavender'],
    // },
    // parfumset: {
    //     type: 'Bag',
    //     color: 'Parfum',
    //     img: 'Parfum.jpg',
    //     param: 'parfum',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // coralset: {
    //     type: 'Bag',
    //     color: 'Coral',
    //     img: 'Coral.jpg',
    //     param: 'coral',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'purple'],
    // },
    // magnificentset: {
    //     type: 'Bag',
    //     color: 'Magnificent',
    //     img: 'Magnificent.jpg',
    //     param: 'magnificent',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['black', 'red'],
    // },
    // meadowset: {
    //     type: 'Bag',
    //     color: 'Meadow',
    //     img: 'Meadow.jpg',
    //     param: 'meadow',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['yellow', 'orange', 'blue'],
    // },
    sunshineset: {
        type: 'Bag',
        color: 'Sunshine Set',
        img: 'SunshineSet.jpg',
        param: 'sunshineset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue', 'yellow', 'red'],
    },
    // beamingset: {
    //     type: 'Bag',
    //     color: 'Beaming',
    //     img: 'Beaming.jpg',
    //     param: 'beaming',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'orange'],
    // },
    // floralwhiteset: {
    //     type: 'Bag',
    //     color: 'Floral White',
    //     img: 'FloralWhite.jpg',
    //     param: 'floralwhite',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: false,
    //     tags: [],
    // },
    // purpleplaidset: {
    //     type: 'Bag',
    //     color: 'Purple Plaid',
    //     img: 'PurplePlaid.jpg',
    //     param: 'purpleplaid',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['lavender', 'violet'],
    // },
    // orangeplaidset: {
    //     type: 'Bag',
    //     color: 'Orange Plaid',
    //     img: 'OrangePlaid.jpg',
    //     param: 'orangeplaid',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: [],
    // },
    // hempset: {
    //     type: 'Bag',
    //     color: 'Hemp',
    //     img: 'Hemp.jpg',
    //     param: 'hemp',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['green'],
    // },
    // stunningset: {
    //     type: 'Bag',
    //     color: 'Stunning',
    //     img: 'Stunning.jpg',
    //     param: 'stunning',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'white'],
    // },
    // fairytaleset: {
    //     type: 'Bag',
    //     color: 'Fairytale',
    //     img: 'Fairytale.jpg',
    //     param: 'fairytale',
    //     price: setPrice,
    //     category: 'floral',
    //     angled: true,
    //     tags: ['blue', 'pink'],
    // },
    // //////////////
    // // MEMORIAL //
    // //////////////
    nationalset: {
        type: 'Bag',
        color: 'National Set',
        img: 'NationalSet.jpg',
        param: 'nationalset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    courageset: {
        type: 'Bag',
        color: 'Courage Set',
        img: 'CourageSet.jpg',
        param: 'courageset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    dutyset: {
        type: 'Bag',
        color: 'Duty Set',
        img: 'DutySet.jpg',
        param: 'dutyset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown'],
    },
    honorset: {
        type: 'Bag',
        color: 'Honor Set',
        img: 'HonorSet.jpg',
        param: 'honorset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    iloveusaset: {
        type: 'Bag',
        color: 'I Love USA Set',
        img: 'ILoveUSASet.jpg',
        param: 'iloveusaset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: [],
    },
    // usaset: {
    //     type: 'Bag',
    //     color: 'USA',
    //     img: 'USA.jpg',
    //     param: 'usa',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['red', 'white', 'blue'],
    // },
    // americanset: {
    //     type: 'Bag',
    //     color: 'American',
    //     img: 'American.jpg',
    //     param: 'american',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['red', 'white', 'blue'],
    // },
    // patriotset: {
    //     type: 'Bag',
    //     color: 'Patriot',
    //     img: 'Patriot.jpg',
    //     param: 'patriot',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['red', 'white', 'blue'],
    // },
    // classicset: {
    //     type: 'Bag',
    //     color: 'Classic',
    //     img: 'Classic.jpg',
    //     param: 'classic',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['red', 'white', 'blue'],
    // },
    // nationalset: {
    //     type: 'Bag',
    //     color: 'National',
    //     img: 'National.jpg',
    //     param: 'national',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['red', 'white', 'blue'],
    // },
    // libertyset: {
    //     type: 'Bag',
    //     color: 'Liberty',
    //     img: 'Liberty.jpg',
    //     param: 'liberty',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // gloryset: {
    //     type: 'Bag',
    //     color: 'Glory',
    //     img: 'Glory.jpg',
    //     param: 'glory',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['black'],
    // },
    // serviceset: {
    //     type: 'Bag',
    //     color: 'Service',
    //     img: 'Service.jpg',
    //     param: 'service',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['green'],
    // },
    // airforceset: {
    //     type: 'Bag',
    //     color: 'United',
    //     img: 'AirForce.jpg',
    //     param: 'airforce',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['brown', 'army'],
    // },
    // marinesset: {
    //     type: 'Bag',
    //     color: 'Marines',
    //     img: 'Marines.jpg',
    //     param: 'marines',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['brown', 'army'],
    // },
    // usnavyset: {
    //     type: 'Bag',
    //     color: 'US Navy',
    //     img: 'USNavy.jpg',
    //     param: 'usnavy',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['blue'],
    // },
    // armyset: {
    //     type: 'Bag',
    //     color: 'Army',
    //     img: 'Army.jpg',
    //     param: 'army',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['blue'],
    // },
    excellenceset: {
        type: 'Bag',
        color: 'Excellence Set',
        img: 'ExcellenceSet.jpg',
        param: 'excellenceset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    // veteranset: {
    //     type: 'Bag',
    //     color: 'Veteran',
    //     img: 'Veteran.jpg',
    //     param: 'veteran',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['brown'],
    // },
    forcesset: {
        type: 'Bag',
        color: 'Forces Set',
        img: 'ForcesSet.jpg',
        param: 'forcesset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    // saluteset: {
    //     type: 'Bag',
    //     color: 'Salute',
    //     img: 'Salute.jpg',
    //     param: 'salute',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['green'],
    // },
    // tagsset: {
    //     type: 'Bag',
    //     color: 'Tags',
    //     img: 'Tags.jpg',
    //     param: 'tags',
    //     price: setPrice,
    //     category: 'patriot',
    //     angled: true,
    //     tags: ['black'],
    // },
    // ////////////
    // // HOLIDAY //
    // ////////////
    slantset: {
        type: 'Bag',
        color: 'Slant Set',
        img: 'SlantSet.jpg',
        param: 'slantset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    buggiesset: {
        type: 'Bag',
        color: 'Buggies Set',
        img: 'BuggiesSet.jpg',
        param: 'buggiesset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    cozyset: {
        type: 'Bag',
        color: 'Cozy Set',
        img: 'CozySet.jpg',
        param: 'cozyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    // crawlerset: {
    //     type: 'Bag',
    //     color: 'Crawler',
    //     img: 'Crawler.jpg',
    //     param: 'crawler',
    //     price: setPrice,
    //     category: 'pattern',
    //     angled: true,
    //     tags: [''],
    // },
    // mistletoeset: {
    //     type: 'Bag',
    //     color: 'Mistletoe',
    //     img: 'Mistletoe.jpg',
    //     param: 'mistletoe',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // poinsettiaset: {
    //     type: 'Bag',
    //     color: 'Poinsettia',
    //     img: 'Poinsettia.jpg',
    //     param: 'poinsettia',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    cheersset: {
        type: 'Bag',
        color: 'Cheers Set',
        img: 'CheersSet.jpg',
        param: 'cheersset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    // santaset: {
    //     type: 'Bag',
    //     color: 'Santa',
    //     img: 'Santa.jpg',
    //     param: 'santa',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    merryset: {
        type: 'Bag',
        color: 'Merry Set',
        img: 'MerrySet.jpg',
        param: 'merryset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    // snowmanset: {
    //     type: 'Bag',
    //     color: 'Snowman',
    //     img: 'Snowman.jpg',
    //     param: 'snowman',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // shinglesset: {
    //     type: 'Bag',
    //     color: 'Shingles',
    //     img: 'Shingles.jpg',
    //     param: 'shingles',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // frostyset: {
    //     type: 'Bag',
    //     color: 'Frosty',
    //     img: 'Frosty.jpg',
    //     param: 'frosty',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // reindeerset: {
    //     type: 'Bag',
    //     color: 'Reindeer',
    //     img: 'Reindeer.jpg',
    //     param: 'reindeer',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // jinglebellsset: {
    //     type: 'Bag',
    //     color: 'Jingle Bells',
    //     img: 'JingleBells.jpg',
    //     param: 'jinglebells',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // merryplaidset: {
    //     type: 'Bag',
    //     color: 'Merry Plaid',
    //     img: 'MerryPlaid.jpg',
    //     param: 'merryplaid',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    // swanset: {
    //     type: 'Bag',
    //     color: 'Swan',
    //     img: 'Swan.jpg',
    //     param: 'swan',
    //     price: setPrice,
    //     category: 'animal',
    //     angled: true,
    //     tags: [''],
    // },
    // snowyset: {
    //     type: 'Bag',
    //     color: 'Snowy',
    //     img: 'Snowy.jpg',
    //     param: 'snowy',
    //     price: setPrice,
    //     category: 'holiday',
    //     angled: true,
    //     tags: [''],
    // },
    fortuneset: {
        type: 'Bag',
        color: 'Fortune Set',
        img: 'FortuneSet.jpg',
        param: 'fortuneset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    angelicset: {
        type: 'Bag',
        color: 'Angelic Set',
        img: 'AngelicSet.jpg',
        param: 'angelicset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: ['blue'],
    },
    jovialset: {
        type: 'Bag',
        color: 'Jovial Set',
        img: 'JovialSet.jpg',
        param: 'jovialset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    pineappleset: {
        type: 'Bag',
        color: 'Pineapple Set',
        img: 'PineappleSet.jpg',
        param: 'pineappleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    greeneryset: {
        type: 'Bag',
        color: 'Greenery Set',
        img: 'GreenerySet.jpg',
        param: 'greeneryset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    giftsset: {
        type: 'Bag',
        color: 'Gifts Set',
        img: 'GiftsSet.jpg',
        param: 'giftsset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    flamingodanceset: {
        type: 'Bag',
        color: 'Flamingo Dance Set',
        img: 'FlamingoDanceSet.jpg',
        param: 'flamingodanceset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
    exoticset: {
        type: 'Bag',
        color: 'Exotic Set',
        img: 'ExoticSet.jpg',
        param: 'exoticset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
};
