import { Designs } from './index';

const setPrice = 40;
export const waistBagPrice = 15;
export const selection: Designs = {
    ////////////
    // SOLIDS //
    ///////////
    denimset: {
        type: 'Bag',
        color: 'Denim Set',
        img: 'DenimSet.jpg',
        param: 'denimset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['jeans', 'blue'],
    },
    // //////////////
    // // BANDANAS //
    // /////////////
    blackbandanaset: {
        type: 'Bag',
        color: 'Black Bandana Set',
        img: 'BlackBandanaSet.jpg',
        param: 'blackbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    navybandanaset: {
        type: 'Bag',
        color: 'Navy Bandana Set',
        img: 'NavyBandanaSet.jpg',
        param: 'navybandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    whitebandanaset: {
        type: 'Bag',
        color: 'White Bandana Set',
        img: 'WhiteBandanaSet.jpg',
        param: 'whitebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    redbandanaset: {
        type: 'Bag',
        color: 'Red Bandana Set',
        img: 'RedBandanaSet.jpg',
        param: 'redbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['pink'],
    },
    pinkbandanaset: {
        type: 'Bag',
        color: 'Pink Bandana Set',
        img: 'PinkBandanaSet.jpg',
        param: 'pinkbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['red'],
    },
    darkbandanaset: {
        type: 'Bag',
        color: 'Dark Bandana Set',
        img: 'DarkBandanaSet.jpg',
        param: 'darkbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    prodigalset: {
        type: 'Bag',
        color: 'Prodigal Set',
        img: 'ProdigalSet.jpg',
        param: 'prodigalset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    silvaset: {
        type: 'Bag',
        color: 'Silva Set',
        img: 'SilvaSet.jpg',
        param: 'silvaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    prosperityset: {
        type: 'Bag',
        color: 'Prosperity Set',
        img: 'ProsperitySet.jpg',
        param: 'prosperityset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    expressionset: {
        type: 'Bag',
        color: 'Expression Set',
        img: 'ExpressionSet.jpg',
        param: 'expressionset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    infinityset: {
        type: 'Bag',
        color: 'Infinity Set',
        img: 'InfinitySet.jpg',
        param: 'infinityset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['green', 'orange'],
    },
    beyondset: {
        type: 'Bag',
        color: 'Beyond Set',
        img: 'BeyondSet.jpg',
        param: 'beyondset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    affinityset: {
        type: 'Bag',
        color: 'Affinity Set',
        img: 'AffinitySet.jpg',
        param: 'affinityset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['white'],
    },
    purplebandanaset: {
        type: 'Bag',
        color: 'Purple Bandana Set',
        img: 'PurpleBandanaSet.jpg',
        param: 'purplebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['purple', 'violet'],
    },
    innerset: {
        type: 'Bag',
        color: 'Inner Set',
        img: 'InnerSet.jpg',
        param: 'innerset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    orangebandanaset: {
        type: 'Bag',
        color: 'Orange Bandana Set',
        img: 'OrangeBandanaSet.jpg',
        param: 'orangebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['orange'],
    },
    yellowbandanaset: {
        type: 'Bag',
        color: 'Yellow Bandana Set',
        img: 'YellowBandanaSet.jpg',
        param: 'yellowbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['yellow'],
    },
    brownbandanaset: {
        type: 'Bag',
        color: 'Brown Bandana Set',
        img: 'BrownBandanaSet.jpg',
        param: 'brownbandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown'],
    },
    beigebandanaset: {
        type: 'Bag',
        color: 'Beige Bandana Set',
        img: 'BeigeBandanaSet.jpg',
        param: 'beigebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown', 'beige'],
    },
    bluebandanaset: {
        type: 'Bag',
        color: 'Blue Bandana Set',
        img: 'BlueBandanaSet.jpg',
        param: 'bluebandanaset',
        price: setPrice,
        category: 'bandana',
        angled: true,
        tags: ['navy'],
    },
    // ///////////////
    // // PATTERNED //
    // //////////////
    hollywoodset: {
        type: 'Bag',
        color: 'Hollywood Set',
        img: 'HollywoodSet.jpg',
        param: 'hollywoodset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    armycamoset: {
        type: 'Bag',
        color: 'Army Camo Set',
        img: 'ArmyCamoSet.jpg',
        param: 'armycamoset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    navycamoset: {
        type: 'Bag',
        color: 'Navy Camo Set',
        img: 'NavyCamoSet.jpg',
        param: 'navycamoset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    camouflageset: {
        type: 'Bag',
        color: 'Camouflage Set',
        img: 'CamouflageSet.jpg',
        param: 'camouflageset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    graceset: {
        type: 'Bag',
        color: 'Grace Set',
        img: 'GraceSet.jpg',
        param: 'graceset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'yellow'],
    },
    redpolkadotset: {
        type: 'Bag',
        color: 'Red Polkadot Set',
        img: 'RedPolkadotSet.jpg',
        param: 'redpolkadotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    greypolkadotset: {
        type: 'Bag',
        color: 'Grey Polkadot Set',
        img: 'GreyPolkadotSet.jpg',
        param: 'greypolkadotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    blotset: {
        type: 'Bag',
        color: 'Blot Set',
        img: 'BlotSet.jpg',
        param: 'blotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    redblotset: {
        type: 'Bag',
        color: 'Red Blot Set',
        img: 'RedBlotSet.jpg',
        param: 'redblotset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    superstarset: {
        type: 'Bag',
        color: 'Superstar Set',
        img: 'SuperstarSet.jpg',
        param: 'superstarset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'colorful'],
    },
    nightskyset: {
        type: 'Bag',
        color: 'Night Sky Set',
        img: 'NightSkySet.jpg',
        param: 'nightskyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    lockeset: {
        type: 'Bag',
        color: 'Locke Set',
        img: 'LockeSet.jpg',
        param: 'lockeset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    esteemedset: {
        type: 'Bag',
        color: 'Esteemed Set',
        img: 'EsteemedSet.jpg',
        param: 'esteemedset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    polkset: {
        type: 'Bag',
        color: 'Polk Set',
        img: 'PolkSet.jpg',
        param: 'polkset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    dreamcatcherset: {
        type: 'Bag',
        color: 'Dreamcatcher Set',
        img: 'DreamcatcherSet.jpg',
        param: 'dreamcatcherset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'red'],
    },
    snowflakeset: {
        type: 'Bag',
        color: 'Snowflake Set',
        img: 'SnowflakeSet.jpg',
        param: 'snowflakeset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: ['blue'],
    },
    comicset: {
        type: 'Bag',
        color: 'Comic Set',
        img: 'ComicSet.jpg',
        param: 'comicset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['white'],
    },
    vivaset: {
        type: 'Bag',
        color: 'Viva Set',
        img: 'VivaSet.jpg',
        param: 'vivaset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    christmasspiritset: {
        type: 'Bag',
        color: 'Christmas Spirit Set',
        img: 'ChristmasSpiritSet.jpg',
        param: 'christmasspiritset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: ['green'],
    },
    ayanset: {
        type: 'Bag',
        color: 'AyanSet',
        img: 'AyanSet.jpg',
        param: 'ayanset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    alloyset: {
        type: 'Bag',
        color: 'Alloy Set',
        img: 'AlloySet.jpg',
        param: 'alloyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['grey'],
    },
    zigzagset: {
        type: 'Bag',
        color: 'Zig Zag Set',
        img: 'ZigZagSet.jpg',
        param: 'zigzagset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    reddottedset: {
        type: 'Bag',
        color: 'Red Dotted Set',
        img: 'RedDottedSet.jpg',
        param: 'reddottedset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'white'],
    },
    kotaset: {
        type: 'Bag',
        color: 'Kota Set',
        img: 'KotaSet.jpg',
        param: 'kotaset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    azuriteset: {
        type: 'Bag',
        color: 'Azurite Set',
        img: 'AzuriteSet.jpg',
        param: 'azuriteset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    marbleset: {
        type: 'Bag',
        color: 'Marble Set',
        img: 'MarbleSet.jpg',
        param: 'marbleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['grey'],
    },
    butterflyset: {
        type: 'Bag',
        color: 'Butterfly Set',
        img: 'ButterflySet.jpg',
        param: 'butterflyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'purple'],
    },
    dazzleset: {
        type: 'Bag',
        color: 'Dazzle Set',
        img: 'DazzleSet.jpg',
        param: 'dazzleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    splashset: {
        type: 'Bag',
        color: 'Splash Set',
        img: 'SplashSet.jpg',
        param: 'splashset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    cherriesset: {
        type: 'Bag',
        color: 'Cherries Set',
        img: 'CherriesSet.jpg',
        param: 'cherriesset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    uniqueset: {
        type: 'Bag',
        color: 'Unique Set',
        img: 'UniqueSet.jpg',
        param: 'uniqueset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'yellow'],
    },
    ascendset: {
        type: 'Bag',
        color: 'Ascend Set',
        img: 'AscendSet.jpg',
        param: 'ascendset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['white', 'blue'],
    },
    starspangledset: {
        type: 'Bag',
        color: 'Star Spangled Set',
        img: 'StarSpangledSet.jpg',
        param: 'starspangledset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'blue'],
    },
    grandset: {
        type: 'Bag',
        color: 'Grand Set',
        img: 'GrandSet.jpg',
        param: 'grandset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    hearthset: {
        type: 'Bag',
        color: 'Hearth Set',
        img: 'HearthSet.jpg',
        param: 'hearthset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    eraset: {
        type: 'Bag',
        color: 'Era Set',
        img: 'EraSet.jpg',
        param: 'eraset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    appleset: {
        type: 'Bag',
        color: 'Apple Set',
        img: 'AppleSet.jpg',
        param: 'appleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    fancyset: {
        type: 'Bag',
        color: 'Fancy Set',
        img: 'FancySet.jpg',
        param: 'fancyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'pink'],
    },
    heelsset: {
        type: 'Bag',
        color: 'Heels Set',
        img: 'HeelsSet.jpg',
        param: 'heelsset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    forestset: {
        type: 'Bag',
        color: 'Forest Set',
        img: 'ForestSet.jpg',
        param: 'forestset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    wildlifeset: {
        type: 'Bag',
        color: 'Wildlife Set',
        img: 'WildlifeSet.jpg',
        param: 'wildlifeset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    blackdottedset: {
        type: 'Bag',
        color: 'Black Dotted Set',
        img: 'BlackDottedSet.jpg',
        param: 'blackdottedset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    spotsset: {
        type: 'Bag',
        color: 'Spots Set',
        img: 'SpotsSet.jpg',
        param: 'spotsset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white', 'dots'],
    },
    gardenerset: {
        type: 'Bag',
        color: 'GardenerSet',
        img: 'GardenerSet.jpg',
        param: 'gardenerset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    musicset: {
        type: 'Bag',
        color: 'Music',
        img: 'Music.jpg',
        param: 'music',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    musicalset: {
        type: 'Bag',
        color: 'Musical Set',
        img: 'MusicalSet.jpg',
        param: 'musicalset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    pinkcamoset: {
        type: 'Bag',
        color: 'Pink Camo Set',
        img: 'PinkCamoSet.jpg',
        param: 'pinkcamoset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    firefighterset: {
        type: 'Bag',
        color: 'Firefighter Set',
        img: 'FirefighterSet.jpg',
        param: 'firefighterset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    ancientset: {
        type: 'Bag',
        color: 'Ancient Set',
        img: 'AncientSet.jpg',
        param: 'ancientset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    shadesset: {
        type: 'Bag',
        color: 'Shades Set',
        img: 'ShadesSet.jpg',
        param: 'shadesset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    spinset: {
        type: 'Bag',
        color: 'Spin Set',
        img: 'SpinSet.jpg',
        param: 'spinset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    woodsset: {
        type: 'Bag',
        color: 'Woods Set',
        img: 'WoodsSet.jpg',
        param: 'woodsset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'black', 'brown'],
    },
    // ////////////
    // // ANIMAL //
    // ///////////
    pawsset: {
        type: 'Bag',
        color: 'Paws Set',
        img: 'PawsSet.jpg',
        param: 'pawsset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    lovableset: {
        type: 'Bag',
        color: 'Lovable Set',
        img: 'LovableSet.jpg',
        param: 'lovableset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    pupperset: {
        type: 'Bag',
        color: 'Pupper Set',
        img: 'PupperSet.jpg',
        param: 'pupperset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    rainbowpawset: {
        type: 'Bag',
        color: 'Rainbow Paw Set',
        img: 'RainbowPawSet.jpg',
        param: 'rainbowpawset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    cobraskinset: {
        type: 'Bag',
        color: 'Cobraskin Set',
        img: 'CobraskinSet.jpg',
        param: 'cobraskinset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    jaguarset: {
        type: 'Bag',
        color: 'Jaguar Set',
        img: 'JaguarSet.jpg',
        param: 'jaguarset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    felineset: {
        type: 'Bag',
        color: 'Feline Set',
        img: 'FelineSet.jpg',
        param: 'felineset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['orange'],
    },
    milkset: {
        type: 'Bag',
        color: 'Milk Set',
        img: 'MilkSet.jpg',
        param: 'milkset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    sweetieset: {
        type: 'Bag',
        color: 'Sweetie Set',
        img: 'SweetieSet.jpg',
        param: 'sweetieset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    tigerset: {
        type: 'Bag',
        color: 'Tiger Set',
        img: 'TigerSet.jpg',
        param: 'tigerset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['orange'],
    },
    cheetahset: {
        type: 'Bag',
        color: 'Cheetah Set',
        img: 'CheetahSet.jpg',
        param: 'cheetahset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'brown', 'orange'],
    },
    snowleopardset: {
        type: 'Bag',
        color: 'Snow Leopard Set',
        img: 'SnowLeopardSet.jpg',
        param: 'snowleopardset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    himaset: {
        type: 'Bag',
        color: 'Hima Set',
        img: 'HimaSet.jpg',
        param: 'himaset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'blue'],
    },
    elephantset: {
        type: 'Bag',
        color: 'Elephant Set',
        img: 'ElephantSet.jpg',
        param: 'elephantset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    arfset: {
        type: 'Bag',
        color: 'Arf Set',
        img: 'ArfSet.jpg',
        param: 'arfset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'blue'],
    },
    jungleset: {
        type: 'Bag',
        color: 'Jungle Set',
        img: 'JungleSet.jpg',
        param: 'jungleset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    toadset: {
        type: 'Bag',
        color: 'Toad Set',
        img: 'ToadSet.jpg',
        param: 'toadset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    goldenunicornset: {
        type: 'Bag',
        color: 'Golden Unicorn Set',
        img: 'GoldenUnicornSet.jpg',
        param: 'goldenunicornset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    unicornset: {
        type: 'Bag',
        color: 'Unicorn Set',
        img: 'UnicornSet.jpg',
        param: 'unicornset',
        price: setPrice,
        category: 'animal',
        angled: false,
        tags: ['pink'],
    },
    unicornpowerset: {
        type: 'Bag',
        color: 'Unicorn Power Set',
        img: 'UnicornPowerSet.jpg',
        param: 'unicornpowerset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    bearburyset: {
        type: 'Bag',
        color: 'Bearbury Set',
        img: 'BearburySet.jpg',
        param: 'bearburyset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    mooset: {
        type: 'Bag',
        color: 'Moo Set',
        img: 'MooSet.jpg',
        param: 'mooset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey', 'black'],
    },
    owlettesset: {
        type: 'Bag',
        color: 'Owlettesset',
        img: 'OwlettesSet.jpg',
        param: 'owlettesset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['grey'],
    },
    madagascarset: {
        type: 'Bag',
        color: 'Madagascar Set',
        img: 'MadagascarSet.jpg',
        param: 'madagascarset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    scoutset: {
        type: 'Bag',
        color: 'Scout Set',
        img: 'ScoutSet.jpg',
        param: 'scoutset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    poochset: {
        type: 'Bag',
        color: 'Pooch Set',
        img: 'PoochSet.jpg',
        param: 'poochset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs'],
    },
    dinoset: {
        type: 'Bag',
        color: 'Dino Set',
        img: 'DinoSet.jpg',
        param: 'dinoset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    // //////////////
    // // HAWAIIAN //
    // //////////////
    hulaset: {
        type: 'Bag',
        color: 'Hula Set',
        img: 'HulaSet.jpg',
        param: 'hulaset',
        price: setPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['pink', 'red', 'green'],
    },
    suaveset: {
        type: 'Bag',
        color: 'Suave Set',
        img: 'SuaveSet.jpg',
        param: 'suaveset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['grey'],
    },
    luauset: {
        type: 'Bag',
        color: 'Luau Set',
        img: 'LuauSet.jpg',
        param: 'luauset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    palmsset: {
        type: 'Bag',
        color: 'Palms Set',
        img: 'PalmsSet.jpg',
        param: 'palmsset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['black'],
    },
    sunsetset: {
        type: 'Bag',
        color: 'Sunset Set',
        img: 'SunsetSet.jpg',
        param: 'sunsetset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    buttercupset: {
        type: 'Bag',
        color: 'Buttercup Set',
        img: 'ButtercupSet.jpg',
        param: 'buttercupset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    glowset: {
        type: 'Bag',
        color: 'Glow Set',
        img: 'GlowSet.jpg',
        param: 'glowset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    canopyset: {
        type: 'Bag',
        color: 'Canopy Set',
        img: 'CanopySet.jpg',
        param: 'canopyset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['pink', 'green'],
    },
    honoluluset: {
        type: 'Bag',
        color: 'Honolulu Set',
        img: 'HonoluluSet.jpg',
        param: 'honoluluset',
        price: setPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red'],
    },
    // ////////////
    // // FLORAL //
    // ////////////
    eleganceset: {
        type: 'Bag',
        color: 'Elegance Set',
        img: 'EleganceSet.jpg',
        param: 'eleganceset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['grey', 'gold', 'yellow'],
    },
    orientset: {
        type: 'Bag',
        color: 'Orient Set',
        img: 'OrientSet.jpg',
        param: 'orientset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red', 'gold', 'yellow'],
    },
    gracefulset: {
        type: 'Bag',
        color: 'Graceful Set',
        img: 'GracefulSet.jpg',
        param: 'gracefulset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    divineset: {
        type: 'Bag',
        color: 'Divine Set',
        img: 'DivineSet.jpg',
        param: 'divineset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    fragrantset: {
        type: 'Bag',
        color: 'Fragrant Set',
        img: 'FragrantSet.jpg',
        param: 'fragrantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    brilliantset: {
        type: 'Bag',
        color: 'Brilliant Set',
        img: 'BrilliantSet.jpg',
        param: 'brilliantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'blue'],
    },
    vibrantset: {
        type: 'Bag',
        color: 'Vibrant Set',
        img: 'VibrantSet.jpg',
        param: 'vibrantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'blue'],
    },
    crystallisset: {
        type: 'Bag',
        color: 'Crystallis Set',
        img: 'CrystallisSet.jpg',
        param: 'crystallisset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'black'],
    },
    ecstaticset: {
        type: 'Bag',
        color: 'Ecstatic Set',
        img: 'EcstaticSet.jpg',
        param: 'ecstaticset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['orange'],
    },
    growthset: {
        type: 'Bag',
        color: 'Growth Set',
        img: 'GrowthSet.jpg',
        param: 'growthset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    curaset: {
        type: 'Bag',
        color: 'Cura Set',
        img: 'CuraSet.jpg',
        param: 'curaset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['maroon', 'red'],
    },
    aretiaset: {
        type: 'Bag',
        color: 'Aretia Set',
        img: 'AretiaSet.jpg',
        param: 'aretiaset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'gold'],
    },
    beautyset: {
        type: 'Bag',
        color: 'Beauty Set',
        img: 'BeautySet.jpg',
        param: 'beautyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'yellow'],
    },
    exquisiteset: {
        type: 'Bag',
        color: 'Exquisite Set',
        img: 'ExquisiteSet.jpg',
        param: 'exquisiteset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    luckset: {
        type: 'Bag',
        color: 'Luck Set',
        img: 'LuckSet.jpg',
        param: 'luckset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    flowerbedset: {
        type: 'Bag',
        color: 'Flowerbed Set',
        img: 'FlowerbedSet.jpg',
        param: 'flowerbedset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    passionset: {
        type: 'Bag',
        color: 'Passion Set',
        img: 'PassionSet.jpg',
        param: 'passionset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    fluorescentset: {
        type: 'Bag',
        color: 'Fluorescent Set',
        img: 'FluorescentSet.jpg',
        param: 'fluorescentset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black'],
    },
    dahliaset: {
        type: 'Bag',
        color: 'Dahlia Set',
        img: 'DahliaSet.jpg',
        param: 'dahliaset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown'],
    },
    marvelset: {
        type: 'Bag',
        color: 'Marvel Set',
        img: 'MarvelSet.jpg',
        param: 'marvelset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    swellset: {
        type: 'Bag',
        color: 'Swell Set',
        img: 'SwellSet.jpg',
        param: 'swellset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    flourishset: {
        type: 'Bag',
        color: 'Flourish Set',
        img: 'FlourishSet.jpg',
        param: 'flourishset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    edenset: {
        type: 'Bag',
        color: 'Eden Set',
        img: 'EdenSet.jpg',
        param: 'edenset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    earthset: {
        type: 'Bag',
        color: 'EarthSet',
        img: 'EarthSet.jpg',
        param: 'earthset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown'],
    },
    pureset: {
        type: 'Bag',
        color: 'Pure Set',
        img: 'PureSet.jpg',
        param: 'pureset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    exuberantset: {
        type: 'Bag',
        color: 'Exuberant Set',
        img: 'ExuberantSet.jpg',
        param: 'exuberantset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    heavenlyset: {
        type: 'Bag',
        color: 'Heavenly Set',
        img: 'HeavenlySet.jpg',
        param: 'heavenlyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    naturalset: {
        type: 'Bag',
        color: 'Natural Set',
        img: 'NaturalSet.jpg',
        param: 'naturalset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow'],
    },
    tranquilset: {
        type: 'Bag',
        color: 'Tranquil Set',
        img: 'TranquilSet.jpg',
        param: 'tranquilset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    bloomset: {
        type: 'Bag',
        color: 'Bloom Set',
        img: 'BloomSet.jpg',
        param: 'bloomset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    bubblyset: {
        type: 'Bag',
        color: 'Bubbly Set',
        img: 'BubblySet.jpg',
        param: 'bubblyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    blossomset: {
        type: 'Bag',
        color: 'Blossom Set',
        img: 'BlossomSet.jpg',
        param: 'blossomset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    bloomingset: {
        type: 'Bag',
        color: 'Blooming Set',
        img: 'BloomingSet.jpg',
        param: 'bloomingset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    rosesset: {
        type: 'Bag',
        color: 'Roses Set',
        img: 'RosesSet.jpg',
        param: 'rosesset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    harmonyset: {
        type: 'Bag',
        color: 'Harmony Set',
        img: 'HarmonySet.jpg',
        param: 'harmonyset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    gardenset: {
        type: 'Bag',
        color: 'Garden Set',
        img: 'GardenSet.jpg',
        param: 'gardenset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    springset: {
        type: 'Bag',
        color: 'Spring Set',
        img: 'SpringSet.jpg',
        param: 'springset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['pink', 'blue', 'green'],
    },
    sunshineset: {
        type: 'Bag',
        color: 'Sunshine Set',
        img: 'SunshineSet.jpg',
        param: 'sunshineset',
        price: setPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue', 'yellow', 'red'],
    },
    // //////////////
    // // MEMORIAL //
    // //////////////
    nationalset: {
        type: 'Bag',
        color: 'National Set',
        img: 'NationalSet.jpg',
        param: 'nationalset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    courageset: {
        type: 'Bag',
        color: 'Courage Set',
        img: 'CourageSet.jpg',
        param: 'courageset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    dutyset: {
        type: 'Bag',
        color: 'Duty Set',
        img: 'DutySet.jpg',
        param: 'dutyset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown'],
    },
    honorset: {
        type: 'Bag',
        color: 'Honor Set',
        img: 'HonorSet.jpg',
        param: 'honorset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    iloveusaset: {
        type: 'Bag',
        color: 'I Love USA Set',
        img: 'ILoveUSASet.jpg',
        param: 'iloveusaset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: [],
    },
    excellenceset: {
        type: 'Bag',
        color: 'Excellence Set',
        img: 'ExcellenceSet.jpg',
        param: 'excellenceset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    forcesset: {
        type: 'Bag',
        color: 'Forces Set',
        img: 'ForcesSet.jpg',
        param: 'forcesset',
        price: setPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    // ////////////
    // // HOLIDAY //
    // ////////////
    slantset: {
        type: 'Bag',
        color: 'Slant Set',
        img: 'SlantSet.jpg',
        param: 'slantset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    buggiesset: {
        type: 'Bag',
        color: 'Buggies Set',
        img: 'BuggiesSet.jpg',
        param: 'buggiesset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    cozyset: {
        type: 'Bag',
        color: 'Cozy Set',
        img: 'CozySet.jpg',
        param: 'cozyset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    cheersset: {
        type: 'Bag',
        color: 'Cheers Set',
        img: 'CheersSet.jpg',
        param: 'cheersset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    merryset: {
        type: 'Bag',
        color: 'Merry Set',
        img: 'MerrySet.jpg',
        param: 'merryset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    fortuneset: {
        type: 'Bag',
        color: 'Fortune Set',
        img: 'FortuneSet.jpg',
        param: 'fortuneset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    angelicset: {
        type: 'Bag',
        color: 'Angelic Set',
        img: 'AngelicSet.jpg',
        param: 'angelicset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: ['blue'],
    },
    jovialset: {
        type: 'Bag',
        color: 'Jovial Set',
        img: 'JovialSet.jpg',
        param: 'jovialset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    pineappleset: {
        type: 'Bag',
        color: 'Pineapple Set',
        img: 'PineappleSet.jpg',
        param: 'pineappleset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    greeneryset: {
        type: 'Bag',
        color: 'Greenery Set',
        img: 'GreenerySet.jpg',
        param: 'greeneryset',
        price: setPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    giftsset: {
        type: 'Bag',
        color: 'Gifts Set',
        img: 'GiftsSet.jpg',
        param: 'giftsset',
        price: setPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    flamingodanceset: {
        type: 'Bag',
        color: 'Flamingo Dance Set',
        img: 'FlamingoDanceSet.jpg',
        param: 'flamingodanceset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
    exoticset: {
        type: 'Bag',
        color: 'Exotic Set',
        img: 'ExoticSet.jpg',
        param: 'exoticset',
        price: setPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
};
