const maskPrice = 12.5;

export const selection = {
    ////////////
    // SOLIDS //
    ///////////
    black: {
        type: 'Mask',
        color: 'Black',
        img: 'Black.jpg',
        param: 'black',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    darkgrey: {
        type: 'Mask',
        color: 'Dark Grey',
        img: 'DarkGrey.jpg',
        param: 'darkgrey',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['black', 'white'],
    },
    grey: {
        type: 'Mask',
        color: 'Grey',
        img: 'Grey.jpg',
        param: 'grey',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['black', 'white'],
    },
    ash: {
        type: 'Mask',
        color: 'Ash',
        img: 'Ash.jpg',
        param: 'ash',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['black', 'grey'],
    },
    navyblue: {
        type: 'Mask',
        color: 'Navy Blue',
        img: 'NavyBlue.jpg',
        param: 'navyblue',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    denim: {
        type: 'Mask',
        color: 'Denim',
        img: 'Denim.jpg',
        param: 'denim',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['jeans', 'blue'],
    },
    pink: {
        type: 'Mask',
        color: 'Pink',
        img: 'Pink.jpg',
        param: 'pink',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['red'],
    },
    white: {
        type: 'Mask',
        color: 'White',
        img: 'White.jpg',
        param: 'white',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    jumper: {
        type: 'Mask',
        color: 'Jumper',
        img: 'Jumper.jpg',
        param: 'jumper',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['green'],
    },
    brown: {
        type: 'Mask',
        color: 'Brown',
        img: 'Brown.jpg',
        param: 'brown',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    lavender: {
        type: 'Mask',
        color: 'Lavender',
        img: 'Lavender.jpg',
        param: 'lavender',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['purple', 'violet'],
    },
    green: {
        type: 'Mask',
        color: 'Green',
        img: 'Green.jpg',
        param: 'green',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    red: {
        type: 'Mask',
        color: 'Red',
        img: 'Red.jpg',
        param: 'red',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['red', 'pink'],
    },
    orange: {
        type: 'Mask',
        color: 'Orange',
        img: 'Orange.jpg',
        param: 'orange',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['orange'],
    },
    yellow: {
        type: 'Mask',
        color: 'Yellow',
        img: 'Yellow.jpg',
        param: 'yellow',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: [],
    },
    peach: {
        type: 'Mask',
        color: 'Peach',
        img: 'Peach.jpg',
        param: 'peach',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['orange'],
    },
    beige: {
        type: 'Mask',
        color: 'Beige',
        img: 'Beige.jpg',
        param: 'beige',
        price: maskPrice,
        category: 'solid',
        angled: true,
        tags: ['orange', 'brown'],
    },
    //////////////
    // BANDANAS //
    /////////////
    blackbandana: {
        type: 'Mask',
        color: 'Black Bandana',
        img: 'BlackBandana.jpg',
        param: 'blackbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    navybandana: {
        type: 'Mask',
        color: 'Navy Bandana',
        img: 'NavyBandana.jpg',
        param: 'navybandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    royalbandana: {
        type: 'Mask',
        color: 'Royal Bandana',
        img: 'RoyalBandana.jpg',
        param: 'royalbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['navy'],
    },
    whitebandana: {
        type: 'Mask',
        color: 'White Bandana',
        img: 'WhiteBandana.jpg',
        param: 'whitebandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    redbandana: {
        type: 'Mask',
        color: 'Red Bandana',
        img: 'RedBandana.jpg',
        param: 'redbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['pink'],
    },
    pinkbandana: {
        type: 'Mask',
        color: 'Pink Bandana',
        img: 'PinkBandana.jpg',
        param: 'pinkbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['red'],
    },
    prodigal: {
        type: 'Mask',
        color: 'Prodigal',
        img: 'Prodigal.jpg',
        param: 'prodigal',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: [],
    },
    infinity: {
        type: 'Mask',
        color: 'Infinity',
        img: 'Infinity.jpg',
        param: 'infinity',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['green', 'orange'],
    },
    reflection: {
        type: 'Mask',
        color: 'Reflection',
        img: 'Reflection.jpg',
        param: 'reflection',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    beyond: {
        type: 'Mask',
        color: 'Beyond',
        img: 'Beyond.jpg',
        param: 'beyond',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    affinity: {
        type: 'Mask',
        color: 'Affinity',
        img: 'Affinity.jpg',
        param: 'affinity',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['white'],
    },
    bluebandana: {
        type: 'Mask',
        color: 'Blue Bandana',
        img: 'BlueBandana.jpg',
        param: 'bluebandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['navy'],
    },
    purplebandana: {
        type: 'Mask',
        color: 'Purple Bandana',
        img: 'PurpleBandana.jpg',
        param: 'purplebandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['purple', 'violet'],
    },
    eternity: {
        type: 'Mask',
        color: 'Eternity',
        img: 'Eternity.jpg',
        param: 'eternity',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['black'],
    },
    sutra: {
        type: 'Mask',
        color: 'Sutra',
        img: 'Sutra.jpg',
        param: 'sutra',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['black', 'purple'],
    },
    creation: {
        type: 'Mask',
        color: 'Creation',
        img: 'Creation.jpg',
        param: 'creation',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['green'],
    },
    orangebandana: {
        type: 'Mask',
        color: 'Orange Bandana',
        img: 'OrangeBandana.jpg',
        param: 'orangebandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['orange'],
    },
    yellowbandana: {
        type: 'Mask',
        color: 'Yellow Bandana',
        img: 'YellowBandana.jpg',
        param: 'yellowbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['yellow'],
    },
    greenbandana: {
        type: 'Mask',
        color: 'Green Bandana',
        img: 'GreenBandana.jpg',
        param: 'greenbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['green'],
    },
    limebandana: {
        type: 'Mask',
        color: 'Lime Bandana',
        img: 'LimeBandana.jpg',
        param: 'limebandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['green'],
    },
    skybandana: {
        type: 'Mask',
        color: 'Sky Bandana',
        img: 'SkyBandana.jpg',
        param: 'skybandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['blue'],
    },
    brownbandana: {
        type: 'Mask',
        color: 'Brown Bandana',
        img: 'BrownBandana.jpg',
        param: 'brownbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown'],
    },
    beigebandana: {
        type: 'Mask',
        color: 'Beige Bandana',
        img: 'BeigeBandana.jpg',
        param: 'beigebandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown', 'beige'],
    },
    hibiscusbandana: {
        type: 'Mask',
        color: 'Hibiscus Bandana',
        img: 'HibiscusBandana.jpg',
        param: 'hibiscusbandana',
        price: maskPrice,
        category: 'bandana',
        angled: true,
        tags: ['brown', 'hibiscus'],
    },
        ///////////////
    // PATTERNED //
    //////////////
    navycamo: {
        type: 'Mask',
        color: 'Navy Camo',
        img: 'NavyCamo.jpg',
        param: 'navycamo',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    armycamo: {
        type: 'Mask',
        color: 'Army Camo',
        img: 'ArmyCamo.jpg',
        param: 'armycamo',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    camouflage: {
        type: 'Mask',
        color: 'Camouflage',
        img: 'Camouflage.jpg',
        param: 'camouflage',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    grace: {
        type: 'Mask',
        color: 'Grace',
        img: 'Grace.jpg',
        param: 'grace',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'yellow'],
    },
    hope: {
        type: 'Mask',
        color: 'Hope',
        img: 'Hope.jpg',
        param: 'hope',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'purple'],
    },
    superstar: {
        type: 'Mask',
        color: 'Superstar',
        img: 'Superstar.jpg',
        param: 'superstar',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'colorful'],
    },
    stars: {
        type: 'Mask',
        color: 'Stars',
        img: 'Stars.jpg',
        param: 'stars',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    starry: {
        type: 'Mask',
        color: 'Starry',
        img: 'Starry.jpg',
        param: 'starry',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    dreamcatcher: {
        type: 'Mask',
        color: 'Dreamcatcher',
        img: 'Dreamcatcher.jpg',
        param: 'dreamcatcher',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'red'],
    },
    snowflake: {
        type: 'Mask',
        color: 'Snowflake',
        img: 'Snowflake.jpg',
        param: 'snowflake',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    calavera: {
        type: 'Mask',
        color: 'Calavera',
        img: 'Calavera.jpg',
        param: 'calavera',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    moonlight: {
        type: 'Mask',
        color: 'Moonlight',
        img: 'Moonlight.jpg',
        param: 'moonlight',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    zigzag: {
        type: 'Mask',
        color: 'Zig Zag',
        img: 'ZigZag.jpg',
        param: 'zigzag',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    checkers: {
        type: 'Mask',
        color: 'Checkers',
        img: 'Checkers.jpg',
        param: 'checkers',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    mortes: {
        type: 'Mask',
        color: 'Mortes',
        img: 'Mortes.jpg',
        param: 'mortes',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    commandments: {
        type: 'Mask',
        color: 'Commandments',
        img: 'Commandments.jpg',
        param: 'commandments',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'yellow', 'gold'],
    },
    rhombus: {
        type: 'Mask',
        color: 'Rhombus',
        img: 'Rhombus.jpg',
        param: 'rhombus',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    minnie: {
        type: 'Mask',
        color: 'Minnie',
        img: 'Minnie.jpg',
        param: 'minnie',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    reddotted: {
        type: 'Mask',
        color: 'Red Dotted',
        img: 'RedDotted.jpg',
        param: 'reddotted',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    paisley: {
        type: 'Mask',
        color: 'Paisley',
        img: 'Paisley.jpg',
        param: 'paisley',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    artifact: {
        type: 'Mask',
        color: 'Artifact',
        img: 'Artifact.jpg',
        param: 'artifact',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    artisanblack: {
        type: 'Mask',
        color: 'Artisan Black',
        img: 'ArtisanBlack.jpg',
        param: 'artisanblack',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    kota: {
        type: 'Mask',
        color: 'Kota',
        img: 'Kota.jpg',
        param: 'kota',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    evening: {
        type: 'Mask',
        color: 'Evening',
        img: 'Evening.jpg',
        param: 'evening',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange', 'brown'],
    },
    butterfly: {
        type: 'Mask',
        color: 'Butterfly',
        img: 'Butterfly.jpg',
        param: 'butterfly',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'purple'],
    },
    hearts: {
        type: 'Mask',
        color: 'Hearts',
        img: 'Hearts.jpg',
        param: 'hearts',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    dazzle: {
        type: 'Mask',
        color: 'Dazzle',
        img: 'Dazzle.jpg',
        param: 'dazzle',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    heiro: {
        type: 'Mask',
        color: 'Heiro',
        img: 'Heiro.jpg',
        param: 'heiro',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    splash: {
        type: 'Mask',
        color: 'Splash',
        img: 'Splash.jpg',
        param: 'splash',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow', 'orange'],
    },
    unique: {
        type: 'Mask',
        color: 'Unique',
        img: 'Unique.jpg',
        param: 'unique',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'yellow'],
    },
    canvas: {
        type: 'Mask',
        color: 'Canvas',
        img: 'Canvas.jpg',
        param: 'canvas',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    starpower: {
        type: 'Mask',
        color: 'Starpower',
        img: 'Starpower.jpg',
        param: 'starpower',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'pink', 'blue'],
    },
    swirl: {
        type: 'Mask',
        color: 'Swirl',
        img: 'Swirl.jpg',
        param: 'swirl',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple'],
    },
    deep: {
        type: 'Mask',
        color: 'Deep',
        img: 'Deep.jpg',
        param: 'deep',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple'],
    },
    illusion: {
        type: 'Mask',
        color: 'Illusion',
        img: 'Illusion.jpg',
        param: 'illusion',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    ascend: {
        type: 'Mask',
        color: 'Ascend',
        img: 'Ascend.jpg',
        param: 'ascend',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['white', 'blue'],
    },
    bubblegum: {
        type: 'Mask',
        color: 'Bubblegum',
        img: 'Bubblegum.jpg',
        param: 'bubblegum',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    starspangled: {
        type: 'Mask',
        color: 'Star Spangled',
        img: 'StarSpangled.jpg',
        param: 'starspangled',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'blue'],
    },
    artistic: {
        type: 'Mask',
        color: 'Artistic',
        img: 'Artistic.jpg',
        param: 'artistic',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    universe: {
        type: 'Mask',
        color: 'Universe',
        img: 'Universe.jpg',
        param: 'universe',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    galaxy: {
        type: 'Mask',
        color: 'Galaxy',
        img: 'Galaxy.jpg',
        param: 'galaxy',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful', 'black'],
    },
    twine: {
        type: 'Mask',
        color: 'Twine',
        img: 'Twine.jpg',
        param: 'twine',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink', 'red'],
    },
    signature: {
        type: 'Mask',
        color: 'Signature',
        img: 'Signature.jpg',
        param: 'signature',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    grand: {
        type: 'Mask',
        color: 'Grand',
        img: 'Grand.jpg',
        param: 'grand',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    sparkle: {
        type: 'Mask',
        color: 'Sparkle',
        img: 'Sparkle.jpg',
        param: 'sparkle',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black'],
    },
    magnetic: {
        type: 'Mask',
        color: 'Magnetic',
        img: 'Magnetic.jpg',
        param: 'magnetic',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue', 'yellow', 'teal'],
    },
    radiant: {
        type: 'Mask',
        color: 'Radiant',
        img: 'Radiant.jpg',
        param: 'radiant',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['yellow', 'orange', 'red'],
    },
    era: {
        type: 'Mask',
        color: 'Era',
        img: 'Era.jpg',
        param: 'era',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    flames: {
        type: 'Mask',
        color: 'Flames',
        img: 'Flames.jpg',
        param: 'flames',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['yellow', 'orange', 'red'],
    },
    nurse: {
        type: 'Mask',
        color: 'Nurse',
        img: 'Nurse.jpg',
        param: 'nurse',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink', 'red'],
    },
    apple: {
        type: 'Mask',
        color: 'Apple',
        img: 'Apple.jpg',
        param: 'apple',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    fancy: {
        type: 'Mask',
        color: 'Fancy',
        img: 'Fancy.jpg',
        param: 'fancy',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'pink'],
    },
    ladybug: {
        type: 'Mask',
        color: 'Ladybug',
        img: 'Ladybug.jpg',
        param: 'ladybug',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red'],
    },
    blackdotted: {
        type: 'Mask',
        color: 'Black Dotted',
        img: 'BlackDotted.jpg',
        param: 'blackdotted',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['dots'],
    },
    spots: {
        type: 'Mask',
        color: 'Spots',
        img: 'Spots.jpg',
        param: 'spots',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white', 'dots'],
    },
    polk: {
        type: 'Mask',
        color: 'Polk',
        img: 'Polk.jpg',
        param: 'polk',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    polkadots: {
        type: 'Mask',
        color: 'Polkadots',
        img: 'Polkadots.jpg',
        param: 'polkadots',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['yellow'],
    },
    gala: {
        type: 'Mask',
        color: 'Gala',
        img: 'Gala.jpg',
        param: 'gala',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'green', 'grey'],
    },
    soccer: {
        type: 'Mask',
        color: 'Soccer',
        img: 'Soccer.jpg',
        param: 'soccer',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    carve: {
        type: 'Mask',
        color: 'Carve',
        img: 'Carve.jpg',
        param: 'carve',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    walnut: {
        type: 'Mask',
        color: 'Walnut',
        img: 'Walnut.jpg',
        param: 'walnut',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['brown'],
    },
    rainbow: {
        type: 'Mask',
        color: 'Rainbow',
        img: 'Rainbow.jpg',
        param: 'rainbow',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    stripe: {
        type: 'Mask',
        color: 'Stripe',
        img: 'Stripe.jpg',
        param: 'stripe',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['colorful'],
    },
    plaid: {
        type: 'Mask',
        color: 'Plaid',
        img: 'Plaid.jpg',
        param: 'plaid',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    tribal: {
        type: 'Mask',
        color: 'Tribal',
        img: 'Tribal.jpg',
        param: 'tribal',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    redplaid: {
        type: 'Mask',
        color: 'Red Plaid',
        img: 'RedPlaid.jpg',
        param: 'redplaid',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'red'],
    },
    enamor: {
        type: 'Mask',
        color: 'Enamor',
        img: 'Enamor.jpg',
        param: 'enamor',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    menace: {
        type: 'Mask',
        color: 'Menace',
        img: 'Menace.jpg',
        param: 'menace',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    artisanred: {
        type: 'Mask',
        color: 'Artisan Red',
        img: 'ArtisanRed.jpg',
        param: 'artisanred',
        price: maskPrice,
        category: 'pattern',
        angled: false,
        tags: ['pink'],
    },
    music: {
        type: 'Mask',
        color: 'Music',
        img: 'Music.jpg',
        param: 'music',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    musical: {
        type: 'Mask',
        color: 'Musical',
        img: 'Musical.jpg',
        param: 'musical',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    pianist: {
        type: 'Mask',
        color: 'Pianist',
        img: 'Pianist.jpg',
        param: 'pianist',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    trumpet: {
        type: 'Mask',
        color: 'Trumpet',
        img: 'Trumpet.jpg',
        param: 'trumpet',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        XLUnavailable: true,
        tags: ['orange'],
    },
    clarinet: {
        type: 'Mask',
        color: 'Clarinet',
        img: 'Clarinet.jpg',
        param: 'clarinet',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    pinkcamo: {
        type: 'Mask',
        color: 'Pink Camo',
        img: 'PinkCamo.jpg',
        param: 'pinkcamo',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['pink'],
    },
    firefighter: {
        type: 'Mask',
        color: 'Firefighter',
        img: 'Firefighter.jpg',
        param: 'firefighter',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange'],
    },
    allure: {
        type: 'Mask',
        color: 'Allure',
        img: 'Allure.jpg',
        param: 'allure',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['purple', 'violet', 'lavender'],
    },
    motion: {
        type: 'Mask',
        color: 'Motion',
        img: 'Motion.jpg',
        param: 'motion',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    native: {
        type: 'Mask',
        color: 'Native',
        img: 'Native.jpg',
        param: 'native',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['orange', 'brown'],
    },
    lavande: {
        type: 'Mask',
        color: 'La Vandé',
        img: 'Lavande.jpg',
        param: 'lavande',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'pink'],
    },
    indus: {
        type: 'Mask',
        color: 'Indus',
        img: 'Indus.jpg',
        param: 'indus',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'orange', 'teal'],
    },
    reza: {
        type: 'Mask',
        color: 'Reza',
        img: 'Reza.jpg',
        param: 'reza',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['green'],
    },
    ancient: {
        type: 'Mask',
        color: 'Ancient',
        img: 'Ancient.jpg',
        param: 'ancient',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    arrow: {
        type: 'Mask',
        color: 'Arrow',
        img: 'Arrow.jpg',
        param: 'arrow',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    shades: {
        type: 'Mask',
        color: 'Shades',
        img: 'Shades.jpg',
        param: 'shades',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [],
    },
    night: {
        type: 'Mask',
        color: 'Night',
        img: 'Night.jpg',
        param: 'night',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['blue'],
    },
    woods: {
        type: 'Mask',
        color: 'Woods',
        img: 'Woods.jpg',
        param: 'woods',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['red', 'black', 'brown'],
    },
    winter: {
        type: 'Mask',
        color: 'Winter',
        img: 'Winter.jpg',
        param: 'winter',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'blue', 'white'],
    },
    decor: {
        type: 'Mask',
        color: 'Decor',
        img: 'Decor.jpg',
        param: 'decor',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['teal', 'orange', 'brown'],
    },
    geo: {
        type: 'Mask',
        color: 'Geo',
        img: 'Geo.jpg',
        param: 'geo',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['teal', 'orange', 'brown'],
    },
    chevrons: {
        type: 'Mask',
        color: 'Chevrons',
        img: 'Chevrons.jpg',
        param: 'chevrons',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: ['black', 'white'],
    },
    ////////////
    // ANIMAL //
    ///////////
    joy: {
        type: 'Mask',
        color: 'Joy',
        img: 'Joy.jpg',
        param: 'joy',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    paws: {
        type: 'Mask',
        color: 'Paws',
        img: 'Paws.jpg',
        param: 'paws',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    lovable: {
        type: 'Mask',
        color: 'Lovable',
        img: 'Lovable.jpg',
        param: 'lovable',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'dog'],
    },
    pupper: {
        type: 'Mask',
        color: 'Pupper',
        img: 'Pupper.jpg',
        param: 'pupper',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'black'],
    },
    doggie: {
        type: 'Mask',
        color: 'Doggie',
        img: 'Doggie.jpg',
        param: 'doggie',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    sweetie: {
        type: 'Mask',
        color: 'Sweetie',
        img: 'Sweetie.jpg',
        param: 'sweetie',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    tiger: {
        type: 'Mask',
        color: 'Tiger',
        img: 'Tiger.jpg',
        param: 'tiger',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['orange'],
    },
    cheetah: {
        type: 'Mask',
        color: 'Cheetah',
        img: 'Cheetah.jpg',
        param: 'cheetah',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'brown'],
    },
    snowleopard: {
        type: 'Mask',
        color: 'Snow Leopard',
        img: 'SnowLeopard.jpg',
        param: 'snowleopard',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    spirit: {
        type: 'Mask',
        color: 'Spirit',
        img: 'Spirit.jpg',
        param: 'spirit',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'blue', 'red'],
    },
    zebra: {
        type: 'Mask',
        color: 'Zebra',
        img: 'Zebra.jpg',
        param: 'zebra',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'white'],
    },
    dalmation: {
        type: 'Mask',
        color: 'Dalmation',
        img: 'Dalmation.jpg',
        param: 'dalmation',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    maldation: {
        type: 'Mask',
        color: 'Maldation',
        img: 'Maldation.jpg',
        param: 'maldation',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    skipper: {
        type: 'Mask',
        color: 'Skipper',
        img: 'Skipper.jpg',
        param: 'skipper',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['red'],
    },
    rawp: {
        type: 'Mask',
        color: 'Rawp',
        img: 'Rawp.jpg',
        param: 'rawp',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs'],
    },
    happy: {
        type: 'Mask',
        color: 'Happy',
        img: 'Happy.jpg',
        param: 'happy',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    bunnies: {
        type: 'Mask',
        color: 'Bunnies',
        img: 'Bunnies.jpg',
        param: 'bunnies',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white'],
    },
    woof: {
        type: 'Mask',
        color: 'Woof',
        img: 'Woof.jpg',
        param: 'woof',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'red'],
    },
    arf: {
        type: 'Mask',
        color: 'Arf',
        img: 'Arf.jpg',
        param: 'arf',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'blue'],
    },
    underwater: {
        type: 'Mask',
        color: 'Underwater',
        img: 'Underwater.jpg',
        param: 'underwater',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    mermaid: {
        type: 'Mask',
        color: 'Mermaid',
        img: 'Mermaid.jpg',
        param: 'mermaid',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    whale: {
        type: 'Mask',
        color: 'Whale',
        img: 'Whale.jpg',
        param: 'whale',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    jungle: {
        type: 'Mask',
        color: 'Jungle',
        img: 'Jungle.jpg',
        param: 'jungle',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    unicorn: {
        type: 'Mask',
        color: 'Unicorn',
        img: 'Unicorn.jpg',
        param: 'unicorn',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    elephant: {
        type: 'Mask',
        color: 'Elephant',
        img: 'Elephant.jpg',
        param: 'elephant',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['pink'],
    },
    bearbury: {
        type: 'Mask',
        color: 'Bearbury',
        img: 'Bearbury.jpg',
        param: 'bearbury',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['green'],
    },
    adorable: {
        type: 'Mask',
        color: 'Adorable',
        img: 'Adorable.jpg',
        param: 'adorable',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['cats'],
    },
    kittens: {
        type: 'Mask',
        color: 'Kittens',
        img: 'Kittens.jpg',
        param: 'kittens',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['cat', 'brown'],
    },
    rainbowclouds: {
        type: 'Mask',
        color: 'Rainbow Clouds',
        img: 'RainbowClouds.jpg',
        param: 'rainbowclouds',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    dawg: {
        type: 'Mask',
        color: 'Dawg',
        img: 'Dawg.jpg',
        param: 'dawg',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog', 'brown'],
    },
    coolio: {
        type: 'Mask',
        color: 'Coolio',
        img: 'Coolio.jpg',
        param: 'coolio',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dog'],
    },
    purr: {
        type: 'Mask',
        color: 'Purr',
        img: 'Purr.jpg',
        param: 'purr',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['red', 'cats'],
    },
    meow: {
        type: 'Mask',
        color: 'Meow',
        img: 'Meow.jpg',
        param: 'meow',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['pink', 'cats'],
    },
    cute: {
        type: 'Mask',
        color: 'Cute',
        img: 'Cute.jpg',
        param: 'cute',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'cat', 'navy'],
    },
    xray: {
        type: 'Mask',
        color: 'X-Ray',
        img: 'X-Ray.jpg',
        param: 'xray',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'cat', 'navy'],
    },
    milk: {
        type: 'Mask',
        color: 'Milk',
        img: 'Milk.jpg',
        param: 'milk',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'black'],
    },
    moo: {
        type: 'Mask',
        color: 'Moo',
        img: 'Moo.jpg',
        param: 'moo',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['grey', 'black'],
    },
    jaguar: {
        type: 'Mask',
        color: 'Jaguar',
        img: 'Jaguar.jpg',
        param: 'jaguar',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    roo: {
        type: 'Mask',
        color: 'Roo',
        img: 'Roo.jpg',
        param: 'roo',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    hunter: {
        type: 'Mask',
        color: 'Hunter',
        img: 'Hunter.jpg',
        param: 'hunter',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    feather: {
        type: 'Mask',
        color: 'Feather',
        img: 'Feather.jpg',
        param: 'feather',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'grey'],
    },
    flamingo: {
        type: 'Mask',
        color: 'Flamingo',
        img: 'Flamingo.jpg',
        param: 'flamingo',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'orange'],
    },
    blackandwhite: {
        type: 'Mask',
        color: 'Black & White',
        img: 'Black&White.jpg',
        param: 'blackandwhite',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['black', 'white'],
    },
    panda: {
        type: 'Mask',
        color: 'Panda',
        img: 'Panda.jpg',
        param: 'panda',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['grey'],
    },
    ranch: {
        type: 'Mask',
        color: 'Ranch',
        img: 'Ranch.jpg',
        param: 'ranch',
        price: maskPrice,
        category: 'animal',
        angled: true,

        tags: ['grey'],
    },
    violetredzebra: {
        type: 'Mask',
        color: 'Violet Red Zebra',
        img: 'VioletRedZebra.jpg',
        param: 'violetredzebra',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['purple', 'magenta'],
    },
    cobra: {
        type: 'Mask',
        color: 'Cobra',
        img: 'Cobra.jpg',
        param: 'cobra',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'orange', 'brown'],
    },
    snakeskin: {
        type: 'Mask',
        color: 'Snakeskin',
        img: 'Snakeskin.jpg',
        param: 'snakeskin',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['animal', 'orange', 'brown'],
    },
    play: {
        type: 'Mask',
        color: 'Play',
        img: 'Play.jpg',
        param: 'play',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'red'],
    },
    eagle: {
        type: 'Mask',
        color: 'Eagle',
        img: 'Eagle.jpg',
        param: 'eagle',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue', 'bird'],
    },
    owls: {
        type: 'Mask',
        color: 'Owls',
        img: 'Owls.jpg',
        param: 'owls',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['brown'],
    },
    owlies: {
        type: 'Mask',
        color: 'Owlies',
        img: 'Owlies.jpg',
        param: 'owlies',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['grey'],
    },
    madagascar: {
        type: 'Mask',
        color: 'Madagascar',
        img: 'Madagascar.jpg',
        param: 'madagascar',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    parrots: {
        type: 'Mask',
        color: 'Parrots',
        img: 'Parrots.jpg',
        param: 'parrots',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['bird', 'colorful'],
    },
    toucan: {
        type: 'Mask',
        color: 'Toucan',
        img: 'Toucan.jpg',
        param: 'toucan',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['bird', 'black'],
    },
    furrballs: {
        type: 'Mask',
        color: 'Furrballs',
        img: 'Furrballs.jpg',
        param: 'furrballs',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['cats'],
    },
    pooch: {
        type: 'Mask',
        color: 'Pooch',
        img: 'Pooch.jpg',
        param: 'pooch',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs'],
    },
    kennel: {
        type: 'Mask',
        color: 'Kennel',
        img: 'Kennel.jpg',
        param: 'kennel',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs', 'brown'],
    },
    barkinglot: {
        type: 'Mask',
        color: 'Barking Lot',
        img: 'BarkingLot.jpg',
        param: 'barkinglot',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['dogs', 'brown'],
    },
    llama: {
        type: 'Mask',
        color: 'Llama',
        img: 'Llama.jpg',
        param: 'llama',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    arctic: {
        type: 'Mask',
        color: 'Arctic',
        img: 'Arctic.jpg',
        param: 'arctic',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    seahorse: {
        type: 'Mask',
        color: 'Seahorse',
        img: 'Seahorse.jpg',
        param: 'seahorse',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    penguins: {
        type: 'Mask',
        color: 'Penguins',
        img: 'Penguins.jpg',
        param: 'penguins',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['white', 'grey', 'blue'],
    },
    dreamy: {
        type: 'Mask',
        color: 'Dreamy',
        img: 'Dreamy.jpg',
        param: 'dreamy',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: ['blue'],
    },
    dino: {
        type: 'Mask',
        color: 'Dino',
        img: 'Dino.jpg',
        param: 'dino',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: [],
    },
    //////////////
    // HAWAIIAN //
    //////////////
    hula: {
        type: 'Mask',
        color: 'Hula',
        img: 'Hula.jpg',
        param: 'hula',
        price: maskPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['pink', 'red', 'green'],
    },
    pond: {
        type: 'Mask',
        color: 'Pond',
        img: 'Pond.jpg',
        param: 'pond',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['blue'],
    },
    suave: {
        type: 'Mask',
        color: 'Suave',
        img: 'Suave.jpg',
        param: 'suave',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['grey'],
    },
    palms: {
        type: 'Mask',
        color: 'Palms',
        img: 'Palms.jpg',
        param: 'palms',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['black'],
    },
    koi: {
        type: 'Mask',
        color: 'Koi',
        img: 'Koi.jpg',
        param: 'koi',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    sunset: {
        type: 'Mask',
        color: 'Sunset',
        img: 'Sunset.jpg',
        param: 'sunset',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['yellow'],
    },
    sky: {
        type: 'Mask',
        color: 'Sky',
        img: 'Sky.jpg',
        param: 'sky',
        price: maskPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['blue'],
    },
    aloha: {
        type: 'Mask',
        color: 'Aloha',
        img: 'Aloha.jpg',
        param: 'aloha',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'orange', 'yellow'],
    },
    glow: {
        type: 'Mask',
        color: 'Glow',
        img: 'Glow.jpg',
        param: 'glow',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red', 'pink'],
    },
    canopy: {
        type: 'Mask',
        color: 'Canopy',
        img: 'Canopy.jpg',
        param: 'canopy',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['pink', 'green'],
    },
    dusk: {
        type: 'Mask',
        color: 'Dusk',
        img: 'Dusk.jpg',
        param: 'dusk',
        price: maskPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['pink'],
    },
    surf: {
        type: 'Mask',
        color: 'Surf',
        img: 'Surf.jpg',
        param: 'surf',
        price: maskPrice,
        category: 'hawaiian',
        angled: false,
        tags: ['grey', 'yellow'],
    },
    honolulu: {
        type: 'Mask',
        color: 'Honolulu',
        img: 'Honolulu.jpg',
        param: 'honolulu',
        price: maskPrice,
        category: 'hawaiian',
        angled: true,
        tags: ['red'],
    },
    ////////////
    // FLORAL //
    ////////////,
    elegant: {
        type: 'Mask',
        color: 'Elegant',
        img: 'Elegant.jpg',
        param: 'elegant',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    divine: {
        type: 'Mask',
        color: 'Divine',
        img: 'Divine.jpg',
        param: 'divine',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    fragrant: {
        type: 'Mask',
        color: 'Fragrant',
        img: 'Fragrant.jpg',
        param: 'fragrant',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    charm: {
        type: 'Mask',
        color: 'Charm',
        img: 'Charm.jpg',
        param: 'charm',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    vibrant: {
        type: 'Mask',
        color: 'Vibrant',
        img: 'Vibrant.jpg',
        param: 'vibrant',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'blue'],
    },
    serene: {
        type: 'Mask',
        color: 'Serene',
        img: 'Serene.jpg',
        param: 'serene',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black'],
    },
    bouquet: {
        type: 'Mask',
        color: 'Bouquet',
        img: 'Bouquet.jpg',
        param: 'bouquet',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'purple'],
    },
    luna: {
        type: 'Mask',
        color: 'Luna',
        img: 'Luna.jpg',
        param: 'luna',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    crystallis: {
        type: 'Mask',
        color: 'Crystallis',
        img: 'Crystallis.jpg',
        param: 'crystallis',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'black'],
    },
    ecstatic: {
        type: 'Mask',
        color: 'Ecstatic',
        img: 'Ecstatic.jpg',
        param: 'ecstatic',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['orange'],
    },
    amethyst: {
        type: 'Mask',
        color: 'Amethyst',
        img: 'Amethyst.jpg',
        param: 'amethyst',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    glisten: {
        type: 'Mask',
        color: 'Glisten',
        img: 'Glisten.jpg',
        param: 'glisten',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    growth: {
        type: 'Mask',
        color: 'Growth',
        img: 'Growth.jpg',
        param: 'growth',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'blue'],
    },
    maroona: {
        type: 'Mask',
        color: 'Maroona',
        img: 'Maroona.jpg',
        param: 'maroona',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['maroon', 'red'],
    },
    cura: {
        type: 'Mask',
        color: 'Cura',
        img: 'Cura.jpg',
        param: 'cura',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['maroon', 'red'],
    },
    wondrous: {
        type: 'Mask',
        color: 'Wondrous',
        img: 'Wondrous.jpg',
        param: 'wondrous',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    aretia: {
        type: 'Mask',
        color: 'Aretia',
        img: 'Aretia.jpg',
        param: 'aretia',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'gold'],
    },
    beauty: {
        type: 'Mask',
        color: 'Beauty',
        img: 'Beauty.jpg',
        param: 'beauty',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'gold', 'yellow'],
    },
    exquisite: {
        type: 'Mask',
        color: 'Exquisite',
        img: 'Exquisite.jpg',
        param: 'exquisite',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    splendid: {
        type: 'Mask',
        color: 'Splendid',
        img: 'Splendid.jpg',
        param: 'splendid',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    luck: {
        type: 'Mask',
        color: 'Luck',
        img: 'Luck.jpg',
        param: 'luck',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    passion: {
        type: 'Mask',
        color: 'Passion',
        img: 'Passion.jpg',
        param: 'passion',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    luxurious: {
        type: 'Mask',
        color: 'Luxurious',
        img: 'Luxurious.jpg',
        param: 'luxurious',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet'],
    },
    miracle: {
        type: 'Mask',
        color: 'Miracle',
        img: 'Miracle.jpg',
        param: 'miracle',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'pink'],
    },
    marvel: {
        type: 'Mask',
        color: 'Marvel',
        img: 'Marvel.jpg',
        param: 'marvel',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    sunlight: {
        type: 'Mask',
        color: 'Sunlight',
        img: 'Sunlight.jpg',
        param: 'sunlight',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['orange'],
    },
    delight: {
        type: 'Mask',
        color: 'Delight',
        img: 'Delight.jpg',
        param: 'delight',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['white'],
    },
    ornate: {
        type: 'Mask',
        color: 'Ornate',
        img: 'Ornate.jpg',
        param: 'ornate',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    swell: {
        type: 'Mask',
        color: 'Swell',
        img: 'Swell.jpg',
        param: 'swell',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    enchanting: {
        type: 'Mask',
        color: 'Enchanting',
        img: 'Enchanting.jpg',
        param: 'enchanting',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    flourish: {
        type: 'Mask',
        color: 'Flourish',
        img: 'Flourish.jpg',
        param: 'flourish',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue'],
    },
    majestic: {
        type: 'Mask',
        color: 'Majestic',
        img: 'Majestic.jpg',
        param: 'majestic',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['red', 'yellow'],
    },
    lovely: {
        type: 'Mask',
        color: 'Lovely',
        img: 'Lovely.jpg',
        param: 'lovely',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    pure: {
        type: 'Mask',
        color: 'Pure',
        img: 'Pure.jpg',
        param: 'pure',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    clarity: {
        type: 'Mask',
        color: 'Clarity',
        img: 'Clarity.jpg',
        param: 'clarity',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    silvermoon: {
        type: 'Mask',
        color: 'Silvermoon',
        img: 'Silvermoon.jpg',
        param: 'silvermoon',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'silver'],
    },
    exuberant: {
        type: 'Mask',
        color: 'Exuberant',
        img: 'Exuberant.jpg',
        param: 'exuberant',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'white'],
    },
    heavenly: {
        type: 'Mask',
        color: 'Heavenly',
        img: 'Heavenly.jpg',
        param: 'heavenly',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    affection: {
        type: 'Mask',
        color: 'Affection',
        img: 'Affection.jpg',
        param: 'affection',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    sapphire: {
        type: 'Mask',
        color: 'Sapphire',
        img: 'Sapphire.jpg',
        param: 'sapphire',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    ruby: {
        type: 'Mask',
        color: 'Ruby',
        img: 'Ruby.jpg',
        param: 'ruby',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    precious: {
        type: 'Mask',
        color: 'Precious',
        img: 'Precious.jpg',
        param: 'precious',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    antique: {
        type: 'Mask',
        color: 'Antique',
        img: 'Antique.jpg',
        param: 'antique',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    natural: {
        type: 'Mask',
        color: 'Natural',
        img: 'Natural.jpg',
        param: 'natural',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow'],
    },
    honey: {
        type: 'Mask',
        color: 'Honey',
        img: 'Honey.jpg',
        param: 'honey',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'yellow'],
    },
    tranquil: {
        type: 'Mask',
        color: 'Tranquil',
        img: 'Tranquil.jpg',
        param: 'tranquil',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['red', 'blue'],
    },
    bloom: {
        type: 'Mask',
        color: 'Bloom',
        img: 'Bloom.jpg',
        param: 'bloom',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    bubbly: {
        type: 'Mask',
        color: 'Bubbly',
        img: 'Bubbly.jpg',
        param: 'bubbly',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    pleasantries: {
        type: 'Mask',
        color: 'Pleasantries',
        img: 'Pleasantries.jpg',
        param: 'pleasantries',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'beige', 'brown'],
    },
    bright: {
        type: 'Mask',
        color: 'Bright',
        img: 'Bright.jpg',
        param: 'bright',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: [''],
    },
    blossom: {
        type: 'Mask',
        color: 'Blossom',
        img: 'Blossom.jpg',
        param: 'blossom',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    harvest: {
        type: 'Mask',
        color: 'Harvest',
        img: 'Harvest.jpg',
        param: 'harvest',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'orange'],
    },
    adore: {
        type: 'Mask',
        color: 'Adore',
        img: 'Adore.jpg',
        param: 'adore',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'pink'],
    },
    bliss: {
        type: 'Mask',
        color: 'Bliss',
        img: 'Bliss.jpg',
        param: 'bliss',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'purple'],
    },
    thrive: {
        type: 'Mask',
        color: 'Thrive',
        img: 'Thrive.jpg',
        param: 'thrive',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'pink'],
    },
    flatter: {
        type: 'Mask',
        color: 'Flatter',
        img: 'Flatter.jpg',
        param: 'flatter',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'yellow'],
    },
    vivid: {
        type: 'Mask',
        color: 'Vivid',
        img: 'Vivid.jpg',
        param: 'vivid',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple'],
    },
    zen: {
        type: 'Mask',
        color: 'Zen',
        img: 'Zen.jpg',
        param: 'zen',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    captivate: {
        type: 'Mask',
        color: 'Captivate',
        img: 'Captivate.jpg',
        param: 'captivate',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'yellow'],
    },
    cherish: {
        type: 'Mask',
        color: 'Cherish',
        img: 'Cherish.jpg',
        param: 'cherish',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'orange'],
    },
    roses: {
        type: 'Mask',
        color: 'Roses',
        img: 'Roses.jpg',
        param: 'roses',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['red'],
    },
    pretty: {
        type: 'Mask',
        color: 'Pretty',
        img: 'Pretty.jpg',
        param: 'pretty',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'blue'],
    },
    floret: {
        type: 'Mask',
        color: 'Floret',
        img: 'Floret.jpg',
        param: 'floret',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green', 'pink', 'purple'],
    },
    harmony: {
        type: 'Mask',
        color: 'Harmony',
        img: 'Harmony.jpg',
        param: 'harmony',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['brown', 'yellow'],
    },
    garden: {
        type: 'Mask',
        color: 'Garden',
        img: 'Garden.jpg',
        param: 'garden',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    bountiful: {
        type: 'Mask',
        color: 'Bountiful',
        img: 'Bountiful.jpg',
        param: 'bountiful',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow'],
    },
    opal: {
        type: 'Mask',
        color: 'Opal',
        img: 'Opal.jpg',
        param: 'opal',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    spring: {
        type: 'Mask',
        color: 'Spring',
        img: 'Spring.jpg',
        param: 'spring',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['pink', 'blue'],
    },
    buoyant: {
        type: 'Mask',
        color: 'Buoyant',
        img: 'Buoyant.jpg',
        param: 'buoyant',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['pink'],
    },
    cultivate: {
        type: 'Mask',
        color: 'Cultivate',
        img: 'Cultivate.jpg',
        param: 'cultivate',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'orange', 'red'],
    },
    treasure: {
        type: 'Mask',
        color: 'Treasure',
        img: 'Treasure.jpg',
        param: 'treasure',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    perfume: {
        type: 'Mask',
        color: 'Perfume',
        img: 'Perfume.jpg',
        param: 'perfume',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['purple', 'violet', 'lavender'],
    },
    parfum: {
        type: 'Mask',
        color: 'Parfum',
        img: 'Parfum.jpg',
        param: 'parfum',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue'],
    },
    coral: {
        type: 'Mask',
        color: 'Coral',
        img: 'Coral.jpg',
        param: 'coral',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'purple'],
    },
    magnificent: {
        type: 'Mask',
        color: 'Magnificent',
        img: 'Magnificent.jpg',
        param: 'magnificent',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['black', 'red'],
    },
    meadow: {
        type: 'Mask',
        color: 'Meadow',
        img: 'Meadow.jpg',
        param: 'meadow',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['yellow', 'orange', 'blue'],
    },
    sunshine: {
        type: 'Mask',
        color: 'Sunshine',
        img: 'Sunshine.jpg',
        param: 'sunshine',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['white', 'blue', 'yellow', 'red'],
    },
    beaming: {
        type: 'Mask',
        color: 'Beaming',
        img: 'Beaming.jpg',
        param: 'beaming',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'orange'],
    },
    floralwhite: {
        type: 'Mask',
        color: 'Floral White',
        img: 'FloralWhite.jpg',
        param: 'floralwhite',
        price: maskPrice,
        category: 'floral',
        angled: false,
        tags: [],
    },
    purpleplaid: {
        type: 'Mask',
        color: 'Purple Plaid',
        img: 'PurplePlaid.jpg',
        param: 'purpleplaid',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['lavender', 'violet'],
    },
    orangeplaid: {
        type: 'Mask',
        color: 'Orange Plaid',
        img: 'OrangePlaid.jpg',
        param: 'orangeplaid',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: [],
    },
    hemp: {
        type: 'Mask',
        color: 'Hemp',
        img: 'Hemp.jpg',
        param: 'hemp',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['green'],
    },
    stunning: {
        type: 'Mask',
        color: 'Stunning',
        img: 'Stunning.jpg',
        param: 'stunning',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'white'],
    },
    fairytale: {
        type: 'Mask',
        color: 'Fairytale',
        img: 'Fairytale.jpg',
        param: 'fairytale',
        price: maskPrice,
        category: 'floral',
        angled: true,
        tags: ['blue', 'pink'],
    },
    //////////////
    // MEMORIAL //
    //////////////
    usa: {
        type: 'Mask',
        color: 'USA',
        img: 'USA.jpg',
        param: 'usa',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    american: {
        type: 'Mask',
        color: 'American',
        img: 'American.jpg',
        param: 'american',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    patriot: {
        type: 'Mask',
        color: 'Patriot',
        img: 'Patriot.jpg',
        param: 'patriot',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    classic: {
        type: 'Mask',
        color: 'Classic',
        img: 'Classic.jpg',
        param: 'classic',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    national: {
        type: 'Mask',
        color: 'National',
        img: 'National.jpg',
        param: 'national',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['red', 'white', 'blue'],
    },
    liberty: {
        type: 'Mask',
        color: 'Liberty',
        img: 'Liberty.jpg',
        param: 'liberty',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    glory: {
        type: 'Mask',
        color: 'Glory',
        img: 'Glory.jpg',
        param: 'glory',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['black'],
    },
    service: {
        type: 'Mask',
        color: 'Service',
        img: 'Service.jpg',
        param: 'service',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    airforce: {
        type: 'Mask',
        color: 'United',
        img: 'AirForce.jpg',
        param: 'airforce',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown', 'army'],
    },
    marines: {
        type: 'Mask',
        color: 'Marines',
        img: 'Marines.jpg',
        param: 'marines',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown', 'army'],
    },
    usnavy: {
        type: 'Mask',
        color: 'US Navy',
        img: 'USNavy.jpg',
        param: 'usnavy',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    army: {
        type: 'Mask',
        color: 'Army',
        img: 'Army.jpg',
        param: 'army',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    excellence: {
        type: 'Mask',
        color: 'Excellence',
        img: 'Excellence.jpg',
        param: 'excellence',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['blue'],
    },
    veteran: {
        type: 'Mask',
        color: 'Veteran',
        img: 'Veteran.jpg',
        param: 'veteran',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['brown'],
    },
    forces: {
        type: 'Mask',
        color: 'Forces',
        img: 'Forces.jpg',
        param: 'forces',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    salute: {
        type: 'Mask',
        color: 'Salute',
        img: 'Salute.jpg',
        param: 'salute',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['green'],
    },
    tags: {
        type: 'Mask',
        color: 'Tags',
        img: 'Tags.jpg',
        param: 'tags',
        price: maskPrice,
        category: 'patriot',
        angled: true,
        tags: ['black'],
    },
    ////////////
    // HOLIDAY //
    ////////////
    spooky: {
        type: 'Mask',
        color: 'Spooky',
        img: 'Spooky.jpg',
        param: 'spooky',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    boo: {
        type: 'Mask',
        color: 'Boo',
        img: 'Boo.jpg',
        param: 'boo',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    crawler: {
        type: 'Mask',
        color: 'Crawler',
        img: 'Crawler.jpg',
        param: 'crawler',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    mistletoe: {
        type: 'Mask',
        color: 'Mistletoe',
        img: 'Mistletoe.jpg',
        param: 'mistletoe',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    poinsettia: {
        type: 'Mask',
        color: 'Poinsettia',
        img: 'Poinsettia.jpg',
        param: 'poinsettia',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    cheers: {
        type: 'Mask',
        color: 'Cheers',
        img: 'Cheers.jpg',
        param: 'cheers',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    santa: {
        type: 'Mask',
        color: 'Santa',
        img: 'Santa.jpg',
        param: 'santa',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    merry: {
        type: 'Mask',
        color: 'Merry',
        img: 'Merry.jpg',
        param: 'merry',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    snowman: {
        type: 'Mask',
        color: 'Snowman',
        img: 'Snowman.jpg',
        param: 'snowman',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    shingles: {
        type: 'Mask',
        color: 'Shingles',
        img: 'Shingles.jpg',
        param: 'shingles',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    frosty: {
        type: 'Mask',
        color: 'Frosty The Snowman',
        img: 'Frosty.jpg',
        param: 'frosty',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    reindeer: {
        type: 'Mask',
        color: 'Reindeer',
        img: 'Reindeer.jpg',
        param: 'reindeer',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    jinglebells: {
        type: 'Mask',
        color: 'Jingle Bells',
        img: 'JingleBells.jpg',
        param: 'jinglebells',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    merryplaid: {
        type: 'Mask',
        color: 'Merry Plaid',
        img: 'MerryPlaid.jpg',
        param: 'merryplaid',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    swan: {
        type: 'Mask',
        color: 'Swan',
        img: 'Swan.jpg',
        param: 'swan',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
    snowy: {
        type: 'Mask',
        color: 'Snowy',
        img: 'Snowy.jpg',
        param: 'snowy',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    fortune: {
        type: 'Mask',
        color: 'Fortune',
        img: 'Fortune.jpg',
        param: 'fortune',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    angelic: {
        type: 'Mask',
        color: 'Angelic',
        img: 'Angelic.jpg',
        param: 'angelic',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    christmastree: {
        type: 'Mask',
        color: 'ChristmasTree',
        img: 'ChristmasTree.jpg',
        param: 'christmastree',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    jovial: {
        type: 'Mask',
        color: 'Jovial',
        img: 'Jovial.jpg',
        param: 'jovial',
        price: maskPrice,
        category: 'pattern',
        angled: false,
        tags: [''],
    },
    pineapple: {
        type: 'Mask',
        color: 'Pineapple',
        img: 'Pineapple.jpg',
        param: 'pineapple',
        price: maskPrice,
        category: 'pattern',
        angled: false,
        tags: [''],
    },
    redpolkadot: {
        type: 'Mask',
        color: 'Red Polkadot',
        img: 'RedPolkadot.jpg',
        param: 'redpolkadot',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    greypolkadot: {
        type: 'Mask',
        color: 'Grey Polkadot',
        img: 'GreyPolkadot.jpg',
        param: 'greypolkadot',
        price: maskPrice,
        category: 'pattern',
        angled: true,
        tags: [''],
    },
    gifts: {
        type: 'Mask',
        color: 'Gifts',
        img: 'Gifts.jpg',
        param: 'gifts',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    snowseason: {
        type: 'Mask',
        color: 'Snow Season',
        img: 'SnowSeason.jpg',
        param: 'snowseason',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    flamingodance: {
        type: 'Mask',
        color: 'Flamingo Dance',
        img: 'FlamingoDance.jpg',
        param: 'flamingodance',
        price: maskPrice,
        category: 'animal',
        angled: true,
        tags: [''],
    },
    choir: {
        type: 'Mask',
        color: 'Choir',
        img: 'Choir.jpg',
        param: 'choir',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    christmas: {
        type: 'Mask',
        color: 'Christmas',
        img: 'Christmas.jpg',
        param: 'christmas',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    ornament: {
        type: 'Mask',
        color: 'Ornament',
        img: 'Ornament.jpg',
        param: 'ornament',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    rosemary: {
        type: 'Mask',
        color: 'Rosemary',
        img: 'Rosemary.jpg',
        param: 'rosemary',
        price: maskPrice,
        category: 'holiday',
        angled: true,
        tags: [''],
    },
    ////////////
    // SHIELDS //
    ////////////
    faceshield: {
        type: 'Shield',
        color: 'Face Shield',
        img: 'FaceShield.jpg',
        param: 'faceshield',
        price: {
            '1x': 7,
            '3x': 15,
            '5x': 20,
            '10x': 30,
        },
        category: 'shield',
        angled: true,
        tags: ['black'],
    },
    ////////////
    // ELASTIC //
    ////////////
    blackelastic: {
        type: 'Elastic',
        color: '1/4" Black Elastic',
        img: 'BlackElastic.jpg',
        param: 'blackelastic',
        price: {
            '25 Yards': 10,
            '85 Yards': 20,
            '200 Yards': 40,
        },
        category: 'custom',
        angled: false,
        tags: ['elastic'],
    },
    whiteelastic: {
        type: 'Elastic',
        color: '1/4" White Elastic',
        img: 'WhiteElastic.jpg',
        param: 'whiteelastic',
        price: {
            '25 Yards': 10,
            '85 Yards': 20,
            '200 Yards': 40,
        },
        category: 'custom',
        angled: false,
        tags: ['elastic'],
    },
};
